Repository IBM/ibm-iam-operator, pull requests merged in 2020-11, with the labels that each got.

#231 Update configmap.go to update OS token length
  pkg/controller/authentication/configmap.go
Labels: approved, size/XS

#232 Updated latest image sha digest for identity-provider image.
  deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#233 Update configmap.go to check length
  pkg/controller/authentication/configmap.go
Labels: approved, size/XS

#235 update with namespace scope configmap
  deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
Labels: approved, size/M

#237 Update secret watcher sha
  deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#236 Update service.go to update mgmt ingress port
  pkg/controller/authentication/service.go
Labels: approved, size/XS

#228 Changed default value of OS_TOKEN_LENGTH to support OCP 4.6 (Issue #42278)
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
Labels: approved, size/S

#229 Auditlogging upgrade
  deploy/crds/operator.ibm.com_authentications_crd.yaml
  deploy/crds/operator.ibm.com_paps_crd.yaml
  deploy/crds/operator.ibm.com_policydecisions_crd.yaml
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/deployment.go
  pkg/controller/pap/containers.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policydecision/containers.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/resources/constants.go
Labels: approved, size/M

#238 inject pod namespace environment variable in oidc client watcher
  deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/role.yaml
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
Labels: approved, size/L

#239 remove syslog tls path from required
  deploy/crds/operator.ibm.com_authentications_crd.yaml
  deploy/crds/operator.ibm.com_paps_crd.yaml
  deploy/crds/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_policydecisions_crd.yaml
Labels: approved, size/M

#240 Update oidc client watcher sha
  deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#241 update shas
  deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#243 Update sha for identity-manager, pap and auth-service
  deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#245 add clients/status to role
  deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/role.yaml
Labels: approved, size/S

#242 Remove namespace hardcoding
  deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
  pkg/apis/operator/v1alpha1/accesspolicies.go
  pkg/controller/authentication/certificate.go
  pkg/controller/authentication/webhook.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/S

#249 bump up operator version
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.7.5/ibm-iam-operator.v3.7.5.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.5/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.5/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.5/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.5/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.5/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.5/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.5/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.1/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.1/ibm-iam-operator.v3.8.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.1/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.1/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.1/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.1/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.1/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.1/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.1/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.1/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  version/version.go
Labels: approved, size/XXL

#247 remove all CRD related code - DO NOT MERGE
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/apis/operator/v1alpha1/oidcclientwatcher_types.go
  pkg/apis/operator/v1alpha1/policycontroller_types.go
  pkg/apis/operator/v1alpha1/register.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
Labels: approved, do-not-merge/hold, size/L

#248 update service during upgrade
  pkg/controller/authentication/service.go
Labels: approved, size/S

#250 Update iam onboarding image after ubi update
  deploy/olm-catalog/ibm-iam-operator/3.8.1/ibm-iam-operator.v3.8.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#246 update ubi images
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, size/XS

#252 Updated iam-policy-controller latest image sha digest.
  deploy/olm-catalog/ibm-iam-operator/3.8.1/ibm-iam-operator.v3.8.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#251 changing pdp and id-mgmt digests
  deploy/olm-catalog/ibm-iam-operator/3.8.1/ibm-iam-operator.v3.8.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#253 update audit image
  deploy/olm-catalog/ibm-iam-operator/3.8.1/ibm-iam-operator.v3.8.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#254 Updated latest image sha digest for IAM operands.
  deploy/olm-catalog/ibm-iam-operator/3.8.1/ibm-iam-operator.v3.8.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#256 udpated the sha of oidcclient-watcher
  deploy/olm-catalog/ibm-iam-operator/3.8.1/ibm-iam-operator.v3.8.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#257 update oidc client watcher sha
  deploy/olm-catalog/ibm-iam-operator/3.8.1/ibm-iam-operator.v3.8.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#258 Update operator.yaml to update sha for idmgmt
  deploy/olm-catalog/ibm-iam-operator/3.8.1/ibm-iam-operator.v3.8.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#260 Update idmgmt errorcode
  deploy/olm-catalog/ibm-iam-operator/3.8.1/ibm-iam-operator.v3.8.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS
