Repository IBM/ibm-iam-operator, pull requests merged in 2020-09, with the labels that each got.

#174 Updated latest image sha digest for platform-auth and identity-provider container images for 3.7.1
  deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#170 adding support for power and z
  deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
Labels: approved, size/XS

#176 Updated new image sha digest for platform-auth, identity-provider and identity-manager container images.
  deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#177 Updated latest image sha digest for IAM operand images.
  deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#160 add MEMORY env var to auth service
  pkg/controller/authentication/containers.go
Labels: approved, size/M

#179 change the order of code to support upgrade
  pkg/controller/authentication/containers.go
Labels: approved, size/XS

#178 Specify default value for bootstrap_userid as kubeadmin
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
Labels: approved, size/XS

#175 Added initIdentityManager container to oidcclient-watcher pod
  deploy/crds/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_oidcclientwatcher_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
  pkg/apis/operator/v1alpha1/oidcclientwatcher_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
Labels: approved, size/L

#180 Add provider issuer url
  deploy/crds/operator.ibm.com_authentications_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.1/operator.ibm.com_authentications_crd.yaml
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
Labels: approved, size/S

#181 Updated latest sha digest for platform-auth and identity-provider images.
  deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#182 Updated latest sha digest for identity-manager image.
  deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#183 support upgrade from beta1 to beta2
  pkg/controller/authentication/configmap.go
Labels: approved, size/XS

#184 Support changing only roks prefix
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
  pkg/controller/authentication/configmap.go
Labels: approved, lgtm, size/S

#186 add timeout for identity provider and identity manager
  pkg/controller/authentication/containers.go
Labels: approved, size/XS

#187 Updated latest image sha digest for IAM operand images.
  deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#188 Updated latest image sha digest for oidcclient-watcher operand image.
  deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#189 Update identity-manager and identity-provider shas
  deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#190 Updated latest image sha digest for identity-provider operand image.
  deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#191 updating sha for identity-manager
  deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#192 update shas
  deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#193 updating PAP sha
  deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#194 Revert "updating PAP sha"
  deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#197 Updated latest image sha digest for IAM operand images.
  deploy/olm-catalog/ibm-iam-operator/3.7.2/ibm-iam-operator.v3.7.2.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#198 updating CSV version for beta and dev channels
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
Labels: approved, size/XS

#199 Updated latest sha digest for IAM operand identity-manager image.
  deploy/olm-catalog/ibm-iam-operator/3.7.2/ibm-iam-operator.v3.7.2.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#200 bump up version
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.7.3/ibm-iam-operator.v3.7.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.3/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.3/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.3/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.3/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.3/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.3/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.3/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  version/version.go
Labels: approved, size/XXL

#201 Updated latest sha digest for all IAM operand images.
  deploy/olm-catalog/ibm-iam-operator/3.7.3/ibm-iam-operator.v3.7.3.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/M

#203 format code
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/apis/operator/v1alpha1/oidcclientwatcher_types.go
  pkg/apis/operator/v1alpha1/pap_types.go
  pkg/apis/operator/v1alpha1/policycontroller_types.go
  pkg/apis/operator/v1alpha1/policydecision_types.go
  pkg/apis/operator/v1alpha1/secretwatcher_types.go
  pkg/apis/operator/v1alpha1/securityonboarding_types.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/constants.go
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/secret.go
  pkg/controller/authentication/webhook.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/containers.go
  pkg/controller/policydecision/containers.go
  pkg/controller/shatag/shatag.go
Labels: approved, size/L

#204 format source code
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/certificate.go
  pkg/controller/authentication/clusterrole.go
  pkg/controller/authentication/clusterrolebinding.go
  pkg/controller/authentication/secret.go
  pkg/controller/authentication/webhook.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
Labels: approved, size/M

#202 add pod antiaffinity
  pkg/controller/authentication/deployment.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
Labels: approved, size/L

#205 Ready to merge: Accept x-frame domain value in operand configuration
  deploy/crds/operator.ibm.com_authentications_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.3/ibm-iam-operator.v3.7.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.3/operator.ibm.com_authentications_crd.yaml
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/controller/authentication/ingress.go
Labels: approved, lgtm, size/S

#208 Revert "Ready to merge: Accept x-frame domain value in operand configuration"
  deploy/crds/operator.ibm.com_authentications_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.3/ibm-iam-operator.v3.7.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.3/operator.ibm.com_authentications_crd.yaml
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/controller/authentication/ingress.go
Labels: approved, size/S

#207 Updated latest image sha digest for IAM operand images.
  deploy/olm-catalog/ibm-iam-operator/3.7.3/ibm-iam-operator.v3.7.3.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#209 Update ubi image
  build/Dockerfile
  build/Dockerfile.ppc64le
Labels: approved, size/XS

#210 Xframe and preferred login changes
  deploy/crds/operator.ibm.com_authentications_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.3/ibm-iam-operator.v3.7.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.3/operator.ibm.com_authentications_crd.yaml
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/ingress.go
Labels: approved, size/M

#211 Update operator.yaml to update sha after preferred login changes
  deploy/olm-catalog/ibm-iam-operator/3.7.3/ibm-iam-operator.v3.7.3.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS
