Repository IBM/ibm-iam-operator, pull requests merged in 2020-10, with the labels that each got.

#214 updating csv to 3.8.0
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  version/version.go
Labels: approved, size/XXL

#216 change version to 3.7.4 to support fixpack
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.7.4/ibm-iam-operator.v3.7.4.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.4/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.4/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.4/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.4/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.4/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.4/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.4/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  version/version.go
Labels: approved, size/S

#217 Updated latest sha digest for identity-manager operand image for CS 3.5.5 release.
  deploy/olm-catalog/ibm-iam-operator/3.7.4/ibm-iam-operator.v3.7.4.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#218 4q CSV updates
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  version/version.go
Labels: approved, size/XXL

#221 Updated latest image sha digest for IAM operand images.
  deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#215 41447/syslog sidecar
  deploy/crds/operator.ibm.com_authentications_crd.yaml
  deploy/crds/operator.ibm.com_paps_crd.yaml
  deploy/crds/operator.ibm.com_policydecisions_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_pap_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_policydecision_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.0/operator.ibm.com_policydecisions_crd.yaml
  deploy/operator.yaml
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/deployment.go
  pkg/controller/pap/containers.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policydecision/containers.go
  pkg/controller/policydecision/policydecision_controller.go
Labels: approved, size/L

#212 Added initAuthService and initIdentityProvider containers to oidcclient-watcher pod
  deploy/crds/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_oidcclientwatcher_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
  pkg/apis/operator/v1alpha1/oidcclientwatcher_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
Labels: approved, size/L

#222 Updated latest image sha digest for IAM operands pap and iam-onboarding images.
  deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#220 Update permissions
  Makefile
  deploy/crds/iam.policies_v1alpha1_iampolicy.yaml
  deploy/crds/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/certificate.go
  pkg/controller/authentication/clusterrole.go
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/job.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/containers.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/containers.go
  pkg/controller/policydecision/policydecision_controller.go
Labels: approved, size/XXL

#224 resolve the errors in CRs related to audit
  deploy/olm-catalog/ibm-iam-operator/3.8.0/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.0/oidc_v1_client_crd.yaml
Labels: approved, size/L

#226 Updated latest image sha digest for identity-manager.
  deploy/olm-catalog/ibm-iam-operator/3.8.0/ibm-iam-operator.v3.8.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#219 Issue41945 check if hosted on public cloud
  pkg/controller/authentication/configmap.go
Labels: approved, size/M

#225 adding 3.7.5 CSV
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.7.5/ibm-iam-operator.v3.7.5.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.5/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.5/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.5/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.5/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.5/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.5/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.5/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  version/version.go
Labels: approved, size/XXL

#227 Changed default value of OS_TOKEN_LENGTH to support OCP 4.6 in 3.7.4 branch (Issue #42278)
  deploy/olm-catalog/ibm-iam-operator/3.7.5/ibm-iam-operator.v3.7.5.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
Labels: approved, size/S
