Repository IBM/ibm-iam-operator, pull requests merged in 2020-06, with the labels that each got.

#114 increase limits to meet needs on ppc64le
  Makefile
  deploy/olm-catalog/ibm-iam-operator/3.6.2/ibm-iam-operator.v3.6.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.2/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.2/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.2/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.2/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.2/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.2/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.2/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  deploy/operator.yaml
  pkg/controller/policycontroller/policycontroller_controller.go
Labels: approved, size/XXL

#115 Update version
  version/version.go
Labels: approved, size/XS

#116 fix permissions for client creation
  deploy/olm-catalog/ibm-iam-operator/3.6.2/ibm-iam-operator.v3.6.2.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, size/S

#117 changing release tag to digest
  deploy/olm-catalog/ibm-iam-operator/3.6.2/ibm-iam-operator.v3.6.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
Labels: approved, size/XS

#118 update version and replaces
  deploy/olm-catalog/ibm-iam-operator/3.6.2/ibm-iam-operator.v3.6.2.clusterserviceversion.yaml
Labels: approved, size/XS

#119 [DO NOT MERGE] updating package.yaml for stable release
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
Labels: approved, size/XS

#120 [DO NOT MERGE] adding files for 3.6.3 operator
  Makefile
  deploy/olm-catalog/ibm-iam-operator/3.6.3/ibm-iam-operator.v3.6.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.3/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.3/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.3/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.3/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.3/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.3/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.3/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
Labels: approved, lgtm, size/XXL

#121 promoting dev to beta
  deploy/olm-catalog/ibm-iam-operator/3.6.3/ibm-iam-operator.v3.6.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  deploy/operator.yaml
Labels: approved, size/S

#123 enable nonce by default
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
Labels: approved, size/XS

#124 3.6.4 csv
  Makefile
  deploy/olm-catalog/ibm-iam-operator/3.6.4/ibm-iam-operator.v3.6.4.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.4/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.4/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.4/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.4/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.4/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.4/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.4/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  version/version.go
Labels: approved, size/XXL

#125 generate masterNodeList dynamically - DO NOT MERGE
  pkg/controller/authentication/containers.go
Labels: approved, size/S

#126 update operand tags
  deploy/olm-catalog/ibm-iam-operator/3.6.4/ibm-iam-operator.v3.6.4.clusterserviceversion.yaml
Labels: approved, size/S

#127 Update image digests for iam operator, auth service, pdp and identity…
  deploy/olm-catalog/ibm-iam-operator/3.6.4/ibm-iam-operator.v3.6.4.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  deploy/operator.yaml
Labels: approved, size/M

#128 Update package
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
Labels: approved, size/XS
