Repository IBM/ibm-iam-operator, pull requests merged in 2020-03, with the labels that each got.

#28 integrate with cert manager
  pkg/apis/operator/v1alpha1/accesspolicies.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/certificate.go
  pkg/controller/authentication/constants.go
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/secret.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/XL

#30 Update ibm-iam-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.5.0/ibm-iam-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, size/XS

#29 change clusterissuer name
  pkg/controller/authentication/certificate.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policydecision/policydecision_controller.go
Labels: approved, size/XS

#31 add openshift user kind to scheme
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/apis/operator/v1alpha1/register.go
Labels: approved, size/XS

#32 register user kind
  pkg/apis/operator/v1alpha1/authentication_types.go
Labels: approved, size/XS

#33 fix user resource ownership
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.5.0/ibm-iam-operator.v3.5.0.clusterserviceversion.yaml
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/user.go
Labels: approved, size/S

#34 delete cluster scoped resources on deleting CR
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/ingress.go
  pkg/controller/authentication/service.go
  pkg/controller/authentication/user.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/containers.go
  pkg/controller/policycontroller/policycontroller_controller.go
Labels: approved, size/L

#35 remove master node list
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.5.0/ibm-iam-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, size/XS

#36 Install IAM operator through ODLM - Doc
  README.md
Labels: approved, size/M

#38 fix redirection problem
  pkg/controller/authentication/ingress.go
Labels: approved, size/S

#39 generate password based on password rule
  go.mod
  go.sum
  pkg/controller/authentication/secret.go
Labels: approved, size/S

#40 reflect recent chart changes into operator code and update image versions
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_oidcclientwatcher_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_pap_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_policycontroller_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_policydecision_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_secretwatcher_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_securityonboarding_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.5.0/ibm-iam-operator.v3.5.0.clusterserviceversion.yaml
  pkg/controller/authentication/containers.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
Labels: approved, size/M

#41 fix inconsistencies
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  pkg/controller/authentication/certificate.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/ingress.go
  pkg/controller/authentication/job.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/L

#43 modify ingress
  pkg/controller/authentication/ingress.go
Labels: approved, size/XS

#44 auto generate credentials
  pkg/controller/authentication/secret.go
Labels: approved, size/S

#42 Nonce property enablement - ConfigMap changes
  deploy/crds/operator.ibm.com_authentications_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.5.0/ibm-iam-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.5.0/operator.ibm.com_authentications_crd.yaml
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/ingress.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/M

#45 Added standard labels/annotations for health check (Issue #36251)
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/job.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/M

#46 add webhook
  deploy/operator.yaml
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/secret.go
  pkg/controller/authentication/webhook.go
Labels: approved, size/L

#47 add cert to csv file
  deploy/olm-catalog/ibm-iam-operator/3.5.0/ibm-iam-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, size/S

#48 update ppc base image
  build/Dockerfile.ppc64le
Labels: approved, size/XS

#49 modify cluster ca mounth path
  pkg/controller/secretwatcher/secretwatcher_controller.go
Labels: approved, size/XS

#50 create registration-json configmap with values
  deploy/olm-catalog/ibm-iam-operator/3.5.0/ibm-iam-operator.v3.5.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/constants.go
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/job.go
  pkg/controller/authentication/secret.go
  pkg/controller/authentication/webhook.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/L

#51 update registration json
  pkg/controller/authentication/configmap.go
Labels: approved, size/XS

#52 use arch of operator node for node affinity
  pkg/controller/authentication/deployment.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
Labels: approved, size/S

#53 update client id and secret generation rule
  pkg/controller/authentication/authentication_controller.go
Labels: approved, size/XS

#54 fix MASTER_HOST variable
  pkg/controller/authentication/containers.go
Labels: approved, size/S

#55 Change management ingress container port to 443
  pkg/controller/authentication/service.go
Labels: approved, lgtm, ok-to-test, size/XS

#56 add metering annotations
  deploy/operator.yaml
Labels: approved, size/XS

#57 fix resource limits to support power arch
  deploy/olm-catalog/ibm-iam-operator/3.5.0/ibm-iam-operator.v3.5.0.clusterserviceversion.yaml
  pkg/controller/secretwatcher/secretwatcher_controller.go
Labels: approved, size/S

#59 change image and channel version
  common/scripts/push-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.5.0/ibm-iam-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  deploy/operator.yaml
Labels: approved, size/M

#61 update audit service image version
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_pap_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_policydecision_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.5.0/ibm-iam-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, size/S

#58 Redhat certification
  .osdk-scorecard.yaml
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  common/Makefile.common.mk
  deploy/olm-catalog/ibm-iam-operator/3.5.0/ibm-iam-operator.v3.5.0.clusterserviceversion.yaml
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/XL
