Repository IBM/ibm-iam-operator, pull requests merged in 2020-07, with the labels that each got.

#129 push a new version for dev
  Makefile
  deploy/olm-catalog/ibm-iam-operator/3.6.5/ibm-iam-operator.v3.6.5.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.5/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.5/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.5/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.5/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.5/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.5/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.5/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  deploy/role.yaml
Labels: approved, size/XXL

#131 Update version.go
  version/version.go
Labels: approved, size/XS

#132 fix permissions
  deploy/olm-catalog/ibm-iam-operator/3.6.5/ibm-iam-operator.v3.6.5.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, size/L

#135 update variables mongo ifix3
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
Labels: size/S

#134 make mongod params configurable
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
Labels: approved, size/S

#136 update to use the new auth service and identity provider images
  deploy/olm-catalog/ibm-iam-operator/3.6.5/ibm-iam-operator.v3.6.5.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#137 Update to use ubi8-minimal/8.2.339
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, size/XS

#138 wip promotion to beta
  deploy/olm-catalog/ibm-iam-operator/3.6.5/ibm-iam-operator.v3.6.5.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  deploy/operator.yaml
Labels: approved, do-not-merge/work-in-progress, size/S

#140 Code changes to update platform-auth-idp configmap with new mongo config variables during upgrade.
  pkg/controller/authentication/configmap.go
Labels: approved, size/S

#141 update iam operator image
  deploy/olm-catalog/ibm-iam-operator/3.6.5/ibm-iam-operator.v3.6.5.clusterserviceversion.yaml
Labels: approved, size/XS

#143 promote beta channel to stable
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
Labels: approved, size/XS

#142 Code changes to update platform-auth-idp configmap with new mongo config variables during upgrade for 3.6.4 branch.
  pkg/controller/authentication/configmap.go
Labels: approved, size/S

#133 move dependencies inside the operator logic
  deploy/olm-catalog/ibm-iam-operator/3.7.0/ibm-iam-operator.v3.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/webhook.go
Labels: approved, size/L
