Repository IBM/ibm-iam-operator, pull requests merged in 2020-02, with the labels that each got.

#2 initial iam operator commit
  Makefile
  OWNERS
  build/Dockerfile
  build/bin/entrypoint
  build/bin/user_setup
  cmd/manager/main.go
  deploy/crds/operator.ibm.com_authentications_crd.yaml
  deploy/crds/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/crds/operator.ibm.com_policydecisions_crd.yaml
  deploy/crds/operator.ibm.com_secretwatchers_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_oidcclientwatcher_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_policydecision_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_secretwatcher_cr.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  go.mod
  go.sum
  hack/boilerplate.go.txt
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/apis/apis.go
  pkg/apis/operator/group.go
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/apis/operator/v1alpha1/doc.go
  pkg/apis/operator/v1alpha1/oidcclientwatcher_types.go
  pkg/apis/operator/v1alpha1/policydecision_types.go
  pkg/apis/operator/v1alpha1/register.go
  pkg/apis/operator/v1alpha1/secretwatcher_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_authentication.go
  pkg/controller/add_oidcclientwatcher.go
  pkg/controller/add_policydecision.go
  pkg/controller/add_secretwatcher.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/certificate.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/ingress.go
  pkg/controller/authentication/job.go
  pkg/controller/authentication/secret.go
  pkg/controller/authentication/service.go
  pkg/controller/controller.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/policydecision/containers.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
  tools.go
  version/version.go
Labels: size/XXL

#3 add clusterroles and rolebindings
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/apis/operator/v1alpha1/oidcclientwatcher_types.go
  pkg/apis/operator/v1alpha1/policydecision_types.go
  pkg/apis/operator/v1alpha1/register.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/certificate.go
  pkg/controller/authentication/clusterrole.go
  pkg/controller/authentication/clusterrolebinding.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/ingress.go
  pkg/controller/authentication/job.go
  pkg/controller/authentication/secret.go
  pkg/controller/authentication/service.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/policydecision/containers.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
Labels: approved, size/XXL

#5 fix build
  Makefile
  build/Dockerfile
  cmd/manager/main.go
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/.hadolint.yml
  common/config/.yamllint.yml
  common/config/mdl.rb
  common/config/sass-lint.yml
  common/config/tslint.json
  common/manifest.yaml
  common/scripts/.githooks/make_lint-all.sh
  common/scripts/.githooks/pre-commit
  common/scripts/codecov.sh
  common/scripts/config_docker.sh
  common/scripts/gobuild.sh
  common/scripts/install-operator-sdk.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/lint_go.sh
  common/scripts/push-csv.sh
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  go.mod
  pkg/apis/apis.go
  pkg/apis/certmanager/group.go
  pkg/apis/certmanager/v1alpha1/certificate_common.go
  pkg/apis/certmanager/v1alpha1/certificate_types.go
  pkg/apis/certmanager/v1alpha1/doc.go
  pkg/apis/certmanager/v1alpha1/register.go
  pkg/apis/certmanager/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/accesspolicies.go
  pkg/apis/operator/v1alpha1/pap_types.go
  pkg/apis/operator/v1alpha1/policycontroller_types.go
  pkg/apis/operator/v1alpha1/securityonboarding_types.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/certificate.go
  pkg/controller/controller.go
  pkg/controller/pap/containers.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
  tools.go
  version/version.go
Labels: approved, size/XL

#6 Update README.md
  README.md
Labels: approved, size/XS

#8 add roles, rolebindings, copy secrets from other namespaces
  deploy/cluster_role.yaml
  deploy/cluster_role_binding.yaml
  deploy/operator.yaml
  deploy/role.yaml
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/secret.go
Labels: approved, size/L

#7 Add ppc and s390 dockerfiles
  Makefile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, lgtm, size/L

#9 fix permission errors and make makefile more usable
  Makefile
  deploy/cluster_role.yaml
  deploy/crds/operator.ibm.com_v1alpha1_oidcclientwatcher_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_secretwatcher_cr.yaml
  deploy/operator.yaml
  pkg/controller/pap/pap_controller.go
  pkg/controller/policydecision/policydecision_controller.go
Labels: approved, size/M

#10 Add csv
  deploy/olm-catalog/ibm-iam-operator/3.5.0/ibm-iam-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.5.0/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.5.0/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.5.0/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.5.0/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.5.0/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.5.0/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.5.0/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
Labels: approved, lgtm, size/XXL

#11 Fix errors to ensure integration to meta operator
  Makefile
  deploy/cluster_role.yaml
  deploy/cluster_role_binding.yaml
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_oidcclientwatcher_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_pap_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_policycontroller_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_policydecision_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_secretwatcher_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_securityonboarding_cr.yaml
  deploy/role_binding.yaml
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/clusterrole.go
  pkg/controller/authentication/clusterrolebinding.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/constants.go
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/job.go
  pkg/controller/authentication/secret.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/containers.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/containers.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/XL

#13 fix csv files
  Makefile
  common/scripts/push-csv.sh
  deploy/crds/operator.ibm.com_v1alpha1_pap_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.5.0/ibm-iam-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, size/L

#14 add required crds
  deploy/olm-catalog/ibm-iam-operator/3.5.0/ibm-iam-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, size/S

#15 changes to respond to deployment in the same namespace
  pkg/controller/authentication/containers.go
  pkg/controller/pap/containers.go
  pkg/controller/policydecision/containers.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/S

#18 add securityonboarding jobs
  Makefile
  deploy/cluster_role_binding.yaml
  pkg/controller/authentication/constants.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/M

#19 Modify to allow namespaced operator to deploy cluster role
  deploy/olm-catalog/ibm-iam-operator/3.5.0/ibm-iam-operator.v3.5.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/M

#20 fix clusterroles and clusterrolebindings
  deploy/cluster_role.yaml
  deploy/cluster_role_binding.yaml
  deploy/olm-catalog/ibm-iam-operator/3.5.0/ibm-iam-operator.v3.5.0.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
Labels: approved, size/L

#21 use ibm-iam-operator service account
  deploy/role_binding.yaml
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/constants.go
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/job.go
  pkg/controller/authentication/secret.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/M

#22 Workaround certissue
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/XS

#23 fix mongo communication
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.5.0/ibm-iam-operator.v3.5.0.clusterserviceversion.yaml
  pkg/controller/authentication/constants.go
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/job.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/M

#24 fix jobs
  Makefile
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  pkg/apis/operator/v1alpha1/accesspolicies.go
  pkg/controller/authentication/constants.go
  pkg/controller/pap/containers.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/M

#25 fix registration script
  pkg/controller/authentication/constants.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/S

#26 fix login
  pkg/controller/authentication/constants.go
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/ingress.go
  pkg/controller/authentication/service.go
  pkg/controller/pap/containers.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/L

#27 add admin user
  go.mod
  go.sum
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/user.go
Labels: approved, size/M
