Repository IBM/ibm-iam-operator, pull requests merged in 2020-04, with the labels that each got.

#62 add dev channel
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
Labels: approved, size/XS

#63 update operator and csv version
  deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.0/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.0/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.0/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.0/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.0/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.0/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.0/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  version/version.go
Labels: approved, size/XXL

#65 fix s390x base image
  build/Dockerfile.s390x
Labels: approved, size/XS

#64 manage operator dependency
  deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#66 remove the required field
  deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#67 Update image registry - DO NOT MERGE
  deploy/crds/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/crds/operator.ibm.com_policycontrollers_crd.yaml
  deploy/crds/operator.ibm.com_secretwatchers_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_oidcclientwatcher_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_policycontroller_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_secretwatcher_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
  pkg/apis/operator/v1alpha1/oidcclientwatcher_types.go
  pkg/apis/operator/v1alpha1/policycontroller_types.go
  pkg/apis/operator/v1alpha1/secretwatcher_types.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
Labels: approved, lgtm, size/M

#68 use operand sa
  Makefile
  deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.0/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.0/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.0/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, lgtm, size/L

#70 remove replaces
  deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, size/XS

#71 use latest operator image until release version is tagged
  deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, size/XS

#72 use latest operator image
  deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#73 Casectl changes
  README.md
  deploy/crds/operator.ibm.com_authentications_crd.yaml
  deploy/crds/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/crds/operator.ibm.com_paps_crd.yaml
  deploy/crds/operator.ibm.com_policycontrollers_crd.yaml
  deploy/crds/operator.ibm.com_policydecisions_crd.yaml
  deploy/crds/operator.ibm.com_secretwatchers_crd.yaml
  deploy/crds/operator.ibm.com_securityonboardings_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_oidcclientwatcher_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_pap_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_policycontroller_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_policydecision_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_secretwatcher_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_securityonboarding_cr.yaml
  deploy/operator.yaml
  deploy/role.yaml
Labels: approved, size/L

#77 add labels for csv 3.6.0
  README.md
  deploy/olm-catalog/ibm-iam-operator/3.6.0/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.0/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.0/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.0/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.0/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.0/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.0/operator.ibm.com_securityonboardings_crd.yaml
Labels: approved, size/M

#78 labels for deploy
  deploy/role.yaml
Labels: approved, lgtm, size/XS

#79 fix csv
  deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, size/S

#74 Update csv
  deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#80 use latest images
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_oidcclientwatcher_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_policydecision_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_secretwatcher_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_securityonboarding_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, size/M

#81 update ubi image
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, size/XS

#83 remove userid in restricted scc
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/S

#84 Updated pap and iam-policy-controller image version for Q22020 release.
  deploy/crds/operator.ibm.com_v1alpha1_pap_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_policycontroller_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, size/XS
