Repository IBM/ibm-iam-operator, pull requests merged in 2020-08, with the labels that each got.

#145 Code changes to integrate images with the new CICD pipeline. (Issue #40018)
  Makefile
  common/scripts/config_docker.sh
Labels: approved, size/S

#146 add clusterrole and clusterrolebinding to support cloudpakswitchers
  pkg/controller/authentication/clusterrole.go
  pkg/controller/authentication/clusterrolebinding.go
Labels: approved, size/S

#147 provide cloudpak switchers access to all authenticated users
  pkg/controller/authentication/clusterrolebinding.go
Labels: approved, size/XS

#149 Remove product version
  deploy/olm-catalog/ibm-iam-operator/3.7.0/ibm-iam-operator.v3.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/job.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/L

#150 increase timeout for auth service
  pkg/controller/authentication/containers.go
Labels: approved, size/XS

#151 standardize CR format
  deploy/crds/operator.ibm.com_policydecisions_crd.yaml
  deploy/crds/operator.ibm.com_securityonboardings_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_policydecision_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_securityonboarding_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.0/ibm-iam-operator.v3.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.0/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.0/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.0/operator.ibm.com_securityonboardings_crd.yaml
  pkg/apis/operator/v1alpha1/policydecision_types.go
  pkg/apis/operator/v1alpha1/securityonboarding_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/L

#152 update crd in csv file
  deploy/olm-catalog/ibm-iam-operator/3.7.0/ibm-iam-operator.v3.7.0.clusterserviceversion.yaml
Labels: approved, size/M

#153 replace cloudpakswitchers with switcheritems
  pkg/controller/authentication/clusterrole.go
Labels: approved, size/XS

#148 Update configmap to set roks parameters
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.0/ibm-iam-operator.v3.7.0.clusterserviceversion.yaml
  pkg/controller/authentication/configmap.go
Labels: approved, size/L

#159 Revert CR standardization changes
  deploy/crds/operator.ibm.com_policydecisions_crd.yaml
  deploy/crds/operator.ibm.com_securityonboardings_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_policydecision_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_securityonboarding_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.0/ibm-iam-operator.v3.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.0/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.0/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.0/operator.ibm.com_securityonboardings_crd.yaml
  pkg/apis/operator/v1alpha1/policydecision_types.go
  pkg/apis/operator/v1alpha1/securityonboarding_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/L

#157 update operand shas
  deploy/olm-catalog/ibm-iam-operator/3.7.0/ibm-iam-operator.v3.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/M

#161 remove init container resource usage from CR
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/deployment.go
  pkg/controller/policydecision/containers.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/M

#156 Default admin dependency removal - operand changes
  deploy/crds/operator.ibm.com_authentications_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.5/operator.ibm.com_authentications_crd.yaml
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
Labels: approved, size/S

#162 Revert "Default admin dependency removal - operand changes (#156)"
  deploy/crds/operator.ibm.com_authentications_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.5/operator.ibm.com_authentications_crd.yaml
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
Labels: size/S

#154 Make scopes configurable in Liberty
  deploy/crds/operator.ibm.com_authentications_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.0/ibm-iam-operator.v3.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.0/operator.ibm.com_authentications_crd.yaml
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
Labels: approved, size/M

#166 Update with new audit logging sha
  deploy/olm-catalog/ibm-iam-operator/3.7.0/ibm-iam-operator.v3.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#165 set default resource values to support upgrade
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/job.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/containers.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/containers.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/L

#167 fix syntax of the csv file
  deploy/olm-catalog/ibm-iam-operator/3.7.0/ibm-iam-operator.v3.7.0.clusterserviceversion.yaml
Labels: approved, size/XS

#168 check lint errors in csv file
  Makefile
  common/scripts/lint-csv.sh
Labels: approved, size/M

#169 Issue40633 - Resolve upgrade issue, make non required
  deploy/crds/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.0/operator.ibm.com_authentications_crd.yaml
  pkg/apis/operator/v1alpha1/authentication_types.go
Labels: approved, size/S

#172 ensure clusterolebinding oidc-admin-binding is removed
  cmd/manager/main.go
  pkg/controller/authentication/authentication_controller.go
Labels: approved, size/S

#171 Updated latest image sha digest for plaform-auth, identity-provider and identity-manager container images.
  deploy/olm-catalog/ibm-iam-operator/3.7.0/ibm-iam-operator.v3.7.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#173 bump up the version to 3.7.1
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.7.1/ibm-iam-operator.v3.7.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.1/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.1/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.1/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.1/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.1/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.1/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.7.1/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  version/version.go
Labels: approved, size/XXL
