Repository IBM/ibm-iam-operator, pull requests merged in 2020-12, with the labels that each got.

#261 Updated latest image sha digest for iam-onboarding image.
  deploy/olm-catalog/ibm-iam-operator/3.8.1/ibm-iam-operator.v3.8.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#262 update sha values and image version.
  deploy/olm-catalog/ibm-iam-operator/3.8.1/ibm-iam-operator.v3.8.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/M

#264 fix to support fips
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.8.2/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.2/ibm-iam-operator.v3.8.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.2/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.2/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.2/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.2/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.2/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.2/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.2/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.2/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  deploy/operator.yaml
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/secret.go
  version/version.go
Labels: approved, size/XXL

#265 fix to support fips
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.8.2/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.2/ibm-iam-operator.v3.8.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.2/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.2/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.2/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.2/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.2/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.2/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.2/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.2/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  deploy/operator.yaml
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/secret.go
  version/version.go
Labels: approved, size/XXL

#266 create new version for q1 2020
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.9.0/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.0/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  version/version.go
Labels: approved, size/XXL

#267 update image version and shas
  deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/M

#269 Updated latest image shas for IAM operand images.
  deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#270 Updated latest image digest sha for identity-manager.
  deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS
