Repository IBM/ibm-iam-operator, pull requests merged in 2020-05, with the labels that each got.

#87 add operand bind info
  deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#86 Cr update --Do not merge
  pkg/controller/authentication/deployment.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
Labels: approved, size/L

#90 update to 8.2-267
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, size/XS

#93 support image digests
  deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/authentication/constants.go
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/job.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
  pkg/controller/shatag/shatag.go
Labels: approved, size/L

#94 Resolved the intermittent issue with client CRD creation (Issue #37325)
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
Labels: approved, size/S

#91 Update README.md
  README.md
Labels: approved, size/L

#92 Issue37314 - update IAM readme
  README.md
Labels: approved, size/L

#88 support CAM - DO NOT MERGE
  deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/secret.go
Labels: approved, size/M

#96 Changed default TimeoutSeconds value to 10 (Issue #37658)
  pkg/controller/authentication/webhook.go
Labels: approved, size/XS

#97 Revert image name
  deploy/crds/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/crds/operator.ibm.com_policycontrollers_crd.yaml
  deploy/crds/operator.ibm.com_secretwatchers_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_oidcclientwatcher_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_policycontroller_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_secretwatcher_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
  pkg/apis/operator/v1alpha1/oidcclientwatcher_types.go
  pkg/apis/operator/v1alpha1/policycontroller_types.go
  pkg/apis/operator/v1alpha1/secretwatcher_types.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
Labels: approved, size/M

#89 Update audit tags
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_pap_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_policydecision_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, size/S

#100 add nginx ingress dependency
  deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, size/XS

#99 Product version
  deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/job.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/S

#101 Update ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, size/M

#102 Code changes to reuse same clientid and secret values on reconcile (Issue #37868)
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/secret.go
Labels: approved, size/S

#103 Update ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, size/XS

#104 use sha instead of tag
  deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/M

#105 2q soft release
  deploy/olm-catalog/ibm-iam-operator/3.6.0/ibm-iam-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#107 2q dev release
  deploy/olm-catalog/ibm-iam-operator/3.6.1/ibm-iam-operator.v3.6.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.1/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.1/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.1/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.1/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.1/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.1/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.6.1/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  version/version.go
Labels: approved, size/XXL

#106 Code changes to customize recursiveSearch config value from configmap variable (Issue #35935)
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
Labels: approved, size/XS

#108 increase resource limits for some speicific pods
  deploy/olm-catalog/ibm-iam-operator/3.6.1/ibm-iam-operator.v3.6.1.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
Labels: approved, size/S

#109 Update configmap platform-auth-idp
  Makefile
  pkg/controller/authentication/configmap.go
Labels: approved, size/M

#110 change code coverage to ensure build passes
  Makefile
Labels: approved, size/XS

#111 fix password generation rule and update shas
  deploy/olm-catalog/ibm-iam-operator/3.6.1/ibm-iam-operator.v3.6.1.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/authentication/secret.go
Labels: approved, size/S

#112 update pdp image sha
  deploy/olm-catalog/ibm-iam-operator/3.6.1/ibm-iam-operator.v3.6.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#113 beta release
  deploy/olm-catalog/ibm-iam-operator/3.6.1/ibm-iam-operator.v3.6.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
Labels: approved, lgtm, size/XS
