Repository IBM/ibm-iam-operator, pull requests merged in 2021-01, with the labels that each got.

#271 Update img with cp4auto changes
  deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#272 Updated identity-manager latest image sha digest.
  deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#273 Update sha kid - issue 42971
  deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#275 Updated latest image digest sha for IAM operand images.
  deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/M

#276 Bump CSV 3.8.3
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.8.3/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.3/ibm-iam-operator.v3.8.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.3/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.3/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.3/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.3/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.3/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.3/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.3/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.3/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  version/version.go
Labels: approved, size/XXL

#277 update ubi images
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, size/XS

#259 remove deprecated labels
  deploy/olm-catalog/ibm-iam-operator/3.8.1/ibm-iam-operator.v3.8.1.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/authentication/deployment.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
Labels: approved, size/S

#278 Cp4auto jwk changes, update operator image with these changes
  deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#279 updating identity-provider sha
  deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#255 adding metadata labels to crds to address certification linter rules
  deploy/crds/iam.policies_v1alpha1_iampolicy.yaml
  deploy/crds/oidc_v1_client_crd.yaml
  deploy/crds/operator.ibm.com_authentications_crd.yaml
  deploy/crds/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/crds/operator.ibm.com_paps_crd.yaml
  deploy/crds/operator.ibm.com_policycontrollers_crd.yaml
  deploy/crds/operator.ibm.com_policydecisions_crd.yaml
  deploy/crds/operator.ibm.com_secretwatchers_crd.yaml
  deploy/crds/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.1/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.1/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.1/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.1/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.1/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.1/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.1/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.1/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.1/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.0/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.0/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_securityonboardings_crd.yaml
Labels: approved, size/L

#285 use latest key kubernetes.io/arch
  deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
Labels: approved, size/XS

#286 remove deprecated labels
  deploy/olm-catalog/ibm-iam-operator/3.8.1/ibm-iam-operator.v3.8.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.3/ibm-iam-operator.v3.8.3.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/authentication/deployment.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
Labels: approved, size/S

#280 sha value update for ibm-iam-operator EUS release
  deploy/olm-catalog/ibm-iam-operator/3.8.3/ibm-iam-operator.v3.8.3.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#287 changes to support v3 channel
  deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
Labels: approved, size/XS

#282 add pod topology constraints - DO NOT MERGE
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/job.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/L

#281 add pod topology constraints - DO NOT MERGE
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/job.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/L

#288 update provider/manager sha value
  deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#289 Update with new name format
  deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/job.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/L

#268 support cloudpak admin role
  pkg/apis/operator/v1alpha1/accesspolicies.go
  pkg/controller/authentication/clusterrole.go
  pkg/controller/authentication/clusterrolebinding.go
Labels: approved, size/L

#291 change image naming to support new cicd template
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/job.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
  pkg/controller/shatag/shatag.go
Labels: approved, size/M

#274 Created configmap data attribute to store SCIM LDAP attributes mapping. (Issue #43337)
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/constants.go
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/deployment.go
Labels: approved, size/M

#292 give permission to bind clusterrole and role to support bootstrap admin user
  deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/deployment.go
Labels: approved, size/M

#293 Code changes to customize auth-service LDAP configuration timeout value from configmap variable for master (Issue #43287)
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
Labels: approved, size/XS
