Repository IBM/ibm-iam-operator, pull requests merged in 2021-12, with the labels that each got.

#449 update from 3.12.2 to 3.13
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.13.0/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.13.0/ibm-iam-operator.v3.13.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.13.0/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.13.0/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.13.0/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.13.0/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.13.0/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.13.0/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.13.0/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.13.0/operator.ibm.com_securityonboardings_crd.yaml
  deploy/operator.yaml
  pkg/controller/authentication/configmap.go
  version/version.go
Labels: size/XXL, approved

#448 Issue51077 - check global cpp configmap
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
Labels: approved, size/M

#450 Remove codeconv
  Makefile
  common/scripts/codecov.sh
Labels: approved, size/L

#452 update from 3.8.5 to 3.8.6
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.8.6/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.6/ibm-iam-operator.v3.8.6.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.6/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.6/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.6/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.6/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.6/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.6/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.6/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.6/operator.ibm.com_securityonboardings_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL, approved
