Repository IBM/ibm-iam-operator, pull requests merged in 2021-11, with the labels that each got.

#433 Update README.md to trigger new master build
  README.md
Labels: size/XS, approved

#434 update iam version for 3.6.6 release
  Makefile
  deploy/olm-catalog/ibm-iam-operator/3.8.5/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.5/ibm-iam-operator.v3.8.5.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.5/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.5/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.5/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.5/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.5/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.5/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.5/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.5/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL, approved

#437 update to 3.6.6
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.8.5/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.5/ibm-iam-operator.v3.8.5.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.5/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.5/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.5/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.5/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.5/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.5/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.5/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.8.5/operator.ibm.com_securityonboardings_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL, approved

#439 Release eus
  base_images.json
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, size/S, needs-ok-to-test

#441 Update config_docker.sh to add edge repo
  common/config/.hadolint.yml
  common/scripts/config_docker.sh
Labels: size/XS, approved

#440 Release lock after 3.13
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.12.2/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.12.2/ibm-iam-operator.v3.12.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.12.2/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.12.2/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.12.2/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.12.2/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.12.2/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.12.2/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.12.2/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.12.2/operator.ibm.com_securityonboardings_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL, approved

#443 Update ibm-iam-operator.v3.8.5.clusterserviceversion.yaml Added Image tags section for CICD automation
  deploy/olm-catalog/ibm-iam-operator/3.8.5/ibm-iam-operator.v3.8.5.clusterserviceversion.yaml
Labels: approved, size/S

#444 Update webhook.go to remove v1beta1
  pkg/controller/authentication/webhook.go
Labels: size/XS, approved

#445 changed IBM Operator image tag for RH Mirroring
  deploy/olm-catalog/ibm-iam-operator/3.12.2/ibm-iam-operator.v3.12.2.clusterserviceversion.yaml
Labels: size/XS, approved

#446 python3 upgrade
  pkg/apis/operator/v1alpha1/accesspolicies.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/M

#447 Update ingress.go
  pkg/controller/authentication/ingress.go
Labels: size/XS, approved
