Repository IBM/ibm-iam-operator, pull requests merged in 2021-07, with the labels that each got.

#385 Preserve unknown fields
  deploy/crds/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/oidc_v1_client_crd.yaml
Labels: approved, size/XS

#388 Update README.md for case bundle
  README.md
Labels: approved, size/XS

#390 update version of operands
  deploy/olm-catalog/ibm-iam-operator/3.11.0/ibm-iam-operator.v3.11.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/M

#387 Chun prem multiple
  deploy/crds/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/ibm-iam-operator.v3.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_authentications_crd.yaml
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/webhook.go
Labels: approved, size/M

#370 Update for ingress api version update
  deploy/operator.yaml
  go.mod
  go.sum
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/clusterrole.go
  pkg/controller/authentication/clusterrolebinding.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/ingress.go
  pkg/controller/authentication/job.go
  pkg/controller/authentication/secret.go
  pkg/controller/authentication/service.go
  pkg/controller/authentication/user.go
  pkg/controller/authentication/webhook.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/XXL

#391 add v1beta - web hook conversion error
  pkg/controller/authentication/webhook.go
Labels: approved, size/XS

#392 Update ibm-iam-operator.v3.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/ibm-iam-operator.v3.11.0.clusterserviceversion.yaml
Labels: approved, size/S

#393 bump operator version to 3.11.1
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.11.1/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.1/ibm-iam-operator.v3.11.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.1/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.1/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.1/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.1/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.1/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.1/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.1/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.1/operator.ibm.com_securityonboardings_crd.yaml
  version/version.go
Labels: approved, size/XXL

#394 Bumpup identity provider for issue 47429
  OWNERS
  deploy/olm-catalog/ibm-iam-operator/3.11.1/ibm-iam-operator.v3.11.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#395 Bump up auth service version to 3.6.1 - after loopback removal
  deploy/olm-catalog/ibm-iam-operator/3.11.1/ibm-iam-operator.v3.11.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#396 Update operator.yaml to bump up operands and move to latest ubi
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  deploy/olm-catalog/ibm-iam-operator/3.11.1/ibm-iam-operator.v3.11.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/M

#397 Update operator.yaml to bump identity manager after build passes
  deploy/olm-catalog/ibm-iam-operator/3.11.1/ibm-iam-operator.v3.11.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#398 Update Dockerfile to move to latest ubi minimal and latest audit 1.0.8
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  deploy/olm-catalog/ibm-iam-operator/3.11.1/ibm-iam-operator.v3.11.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S
