Repository IBM/ibm-iam-operator, pull requests merged in 2021-08, with the labels that each got.

#399 opt in and use common ibm base images
  base-images.json
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  common/config/.hadolint.yml
Labels: approved, size/S

#400 Update config_docker.sh
  common/scripts/config_docker.sh
Labels: approved, size/XS

#401 Update Dockerfile
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, size/XS

#402 Update operator.yaml to increase request for ibm-iam-operator
  deploy/operator.yaml
Labels: size/XS, approved

#403 update build params
  Makefile
Labels: size/XS, approved

#404 Rename base-images.json to base_images.json
  base-images.json
  base_images.json
Labels: size/XS, approved

#405 Automate next csv and update to 3.11.2, update operand versions.
  Makefile
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/scripts/lint-csv.sh
  common/scripts/next-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.11.2/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.2/ibm-iam-operator.v3.11.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.2/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.2/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.2/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.2/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.2/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.2/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.2/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.2/operator.ibm.com_securityonboardings_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL, approved
