Repository IBM/ibm-iam-operator, pull requests merged in 2021-03, with the labels that each got.

#316 Add permission to create delete rolebinding
  deploy/olm-catalog/ibm-iam-operator/3.9.1/ibm-iam-operator.v3.9.1.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, size/S

#317 Update ibm-iam-operator.v3.9.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.1/ibm-iam-operator.v3.9.1.clusterserviceversion.yaml
Labels: approved, size/XS

#315 Added IDENTITY_MGMT_URL to auth-pdp container. (Issue #44579)
  pkg/controller/policydecision/containers.go
Labels: approved, size/XS

#318 Q121 sha updates
  deploy/olm-catalog/ibm-iam-operator/3.9.1/ibm-iam-operator.v3.9.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#320 preserve cert manager label in pod spec
  pkg/controller/authentication/deployment.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
Labels: approved, size/S

#321 update to v3.9.2
  Makefile
  README.md
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.9.2/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.2/ibm-iam-operator.v3.9.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.2/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.2/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.2/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.2/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.2/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.2/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.2/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.2/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  version/version.go
Labels: approved, size/XXL

#322 update to 3.10.0
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.10.0/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.10.0/ibm-iam-operator.v3.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.10.0/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.10.0/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.10.0/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.10.0/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.10.0/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.10.0/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.10.0/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.10.0/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  version/version.go
Labels: approved, size/XXL

#319 update webhook on upgrade
  pkg/controller/authentication/webhook.go
Labels: approved, size/M

#328 update webhook on upgrade for EUS branch
  pkg/controller/authentication/webhook.go
Labels: approved, size/M

#327 update webhook on upgrade for latest release
  pkg/controller/authentication/webhook.go
Labels: approved, size/M

#323 Updated identity-manager version for 3.7.1 Fixpack release.
  deploy/olm-catalog/ibm-iam-operator/3.9.2/ibm-iam-operator.v3.9.2.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#324 Updated identity-manager version for master.
  deploy/olm-catalog/ibm-iam-operator/3.10.0/ibm-iam-operator.v3.10.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#329 update provider and oidclient-watcher version
  deploy/olm-catalog/ibm-iam-operator/3.10.0/ibm-iam-operator.v3.10.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#330 Updated provider and oidclient-watcher latest version for 3.7.1 Fixpack release.
  deploy/olm-catalog/ibm-iam-operator/3.9.2/ibm-iam-operator.v3.9.2.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#332 Update replace version
  deploy/olm-catalog/ibm-iam-operator/3.10.0/ibm-iam-operator.v3.10.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#331 update ubi image to fix vulnerabilites
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, size/XS

#334 Updated pdp image latest version for master.
  deploy/olm-catalog/ibm-iam-operator/3.10.0/ibm-iam-operator.v3.10.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#333 Updated pdp image latest version for EUS release branch.
  deploy/olm-catalog/ibm-iam-operator/3.9.2/ibm-iam-operator.v3.9.2.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#336 update version for operand after lodash fix in 3.9.2
  deploy/olm-catalog/ibm-iam-operator/3.9.2/ibm-iam-operator.v3.9.2.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#335 update version with lodash fixes to master
  deploy/olm-catalog/ibm-iam-operator/3.10.0/ibm-iam-operator.v3.10.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#340 Update version to 3.8.3 in csv
  deploy/olm-catalog/ibm-iam-operator/3.8.3/ibm-iam-operator.v3.8.3.clusterserviceversion.yaml
Labels: approved, size/XS

#341 Updated iam-onboarding image latest version for master branch.
  deploy/olm-catalog/ibm-iam-operator/3.10.0/ibm-iam-operator.v3.10.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS
