Repository IBM/ibm-iam-operator, pull requests merged in 2021-09, with the labels that each got.

#408 Chun add attributemapping flag
  deploy/crds/operator.ibm.com_authentications_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.2/operator.ibm.com_authentications_crd.yaml
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
Labels: approved, size/S

#409 Upgrade go
  go.mod
  go.sum
Labels: approved, size/M

#410 Revert "Update webhook.go" to use v1beta1
  pkg/controller/authentication/webhook.go
Labels: size/XS, approved

#411 update next-csv.sh bump up version to 3.12.0 for CS 3.12
  Makefile
  common/scripts/lint-csv.sh
  common/scripts/next-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.12.0/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.12.0/ibm-iam-operator.v3.12.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.12.0/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.12.0/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.12.0/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.12.0/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.12.0/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.12.0/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.12.0/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.12.0/operator.ibm.com_securityonboardings_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL, approved

#406 Update ibm-iam-operator.v3.11.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.2/ibm-iam-operator.v3.11.2.clusterserviceversion.yaml
Labels: size/XS, approved

#412 Revert "Update ibm-iam-operator.v3.11.2.clusterserviceversion.yaml"
  deploy/olm-catalog/ibm-iam-operator/3.11.2/ibm-iam-operator.v3.11.2.clusterserviceversion.yaml
Labels: size/XS, approved

#413 update to 4.0.0+k for project k pipeline work
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/4.0.0+k/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0+k/ibm-iam-operator.v4.0.0+k.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0+k/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0+k/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0+k/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0+k/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0+k/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0+k/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0+k/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0+k/operator.ibm.com_securityonboardings_crd.yaml
  version/version.go
Labels: size/XXL, approved

#414 update version to be 4.0.0-k
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/4.0.0-k/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0-k/ibm-iam-operator.v4.0.0-k.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0-k/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0-k/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0-k/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0-k/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0-k/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0-k/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0-k/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0-k/operator.ibm.com_securityonboardings_crd.yaml
  version/version.go
Labels: size/XS, approved, lgtm

#415 Update ibm-iam-operator.v4.0.0-k.clusterserviceversion.yaml to update replaces
  deploy/olm-catalog/ibm-iam-operator/4.0.0-k/ibm-iam-operator.v4.0.0-k.clusterserviceversion.yaml
Labels: size/XS, approved

#419 Update ibm-iam-operator.v4.0.0-k.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0-k/ibm-iam-operator.v4.0.0-k.clusterserviceversion.yaml
Labels: size/XS, approved

#418 Update webhook.go to v1 review version again
  pkg/controller/authentication/webhook.go
Labels: size/XS, approved
