Repository IBM/ibm-iam-operator, pull requests merged in 2021-02, with the labels that each got.

#294 support auto sha update for EUS release
  deploy/olm-catalog/ibm-iam-operator/3.8.3/ibm-iam-operator.v3.8.3.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/job.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
  pkg/controller/shatag/shatag.go
Labels: approved, size/L

#296 update operator.yaml with image names
  deploy/operator.yaml
Labels: approved, size/S

#290 mount root ca certs
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
Labels: approved, size/S

#297 update copyright
  pkg/apis/operator/v1alpha1/accesspolicies.go
  pkg/controller/authentication/clusterrole.go
  pkg/controller/authentication/clusterrolebinding.go
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/job.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
  pkg/controller/shatag/shatag.go
Labels: approved, size/S

#295 Ibmid saas flag
  deploy/crds/operator.ibm.com_authentications_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_authentications_crd.yaml
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
Labels: approved, size/S

#299 Add zen service id to bindinfo
  deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#300 Issue44140 - update audit syslog image to version 1.0.5
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_pap_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_policydecision_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#302 update security-repos for node and golang version fix
  deploy/olm-catalog/ibm-iam-operator/3.8.3/ibm-iam-operator.v3.8.3.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#301 preserve cert manager label in pod spec
  pkg/controller/authentication/deployment.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
Labels: approved, size/S

#303 give cloudpak admin access to must gather
  pkg/controller/authentication/clusterrole.go
Labels: approved, size/XS

#305 Update bindinfo key to protected
  deploy/olm-catalog/ibm-iam-operator/3.9.0/ibm-iam-operator.v3.9.0.clusterserviceversion.yaml
Labels: approved, size/XS

#306 Update Makefile to use v1.0.3 version manifest tool
  Makefile
Labels: approved, size/XS

#307 Update Makefile to use v1.0.3 version manifest tool for 3.8 EUS branch.
  Makefile
Labels: approved, size/XS

#304 add annotation for automated ca cert data insertion
  pkg/controller/authentication/webhook.go
Labels: approved, size/S

#308 restart job on upgrade
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/M

#309 sync crds in deploy folder with the ones in olm catalog
  deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.0/operator.ibm.com_policydecisions_crd.yaml
Labels: approved, size/M

#310 Resolved issue with scim mapping json.
  pkg/controller/authentication/constants.go
Labels: approved, size/XS

#298 Changed SCIM default mapping of displayName to cn(full name)
  pkg/controller/authentication/constants.go
Labels: approved, size/XS

#311 bump up version to 3.9.1
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.9.1/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.1/ibm-iam-operator.v3.9.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.1/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.1/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.1/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.1/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.1/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.1/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.1/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.9.1/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/ibm-iam-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, size/XXL

#312 update pap version
  deploy/olm-catalog/ibm-iam-operator/3.9.1/ibm-iam-operator.v3.9.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#313 Issue44850 bumpup oidcclient-watcher
  deploy/olm-catalog/ibm-iam-operator/3.9.1/ibm-iam-operator.v3.9.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#314 Update containers.go to expose SAAS variable for manager
  pkg/controller/authentication/containers.go
Labels: approved, size/XS
