Repository IBM/ibm-iam-operator, pull requests merged in 2021-06, with the labels that each got.

#369 Code changes to handle uninstall of cluster resources in case of multiple instances of IAM (Issue #45718)
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/clusterrole.go
  pkg/controller/authentication/clusterrolebinding.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/resources/utils.go
Labels: approved, size/XL

#371 Update Dockerfile - to latest ubi 8
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, size/XS

#372 update to 3.11.0 for common services 3.9 and cd pipeline
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.11.0/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/ibm-iam-operator.v3.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_securityonboardings_crd.yaml
  version/version.go
Labels: approved, size/XXL

#376 Update ibm-iam-operator.v3.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/ibm-iam-operator.v3.11.0.clusterserviceversion.yaml
Labels: approved, size/XS

#377 update operator version to 3.11.0
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.11.0/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/ibm-iam-operator.v3.11.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_securityonboardings_crd.yaml
  version/version.go
Labels: approved, size/XXL

#379 bump up iam future version 4.0.0
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/4.0.0/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_securityonboardings_crd.yaml
  version/version.go
Labels: approved, size/XXL

#381 Update minKubeVersion in csv
  deploy/olm-catalog/ibm-iam-operator/3.11.0/ibm-iam-operator.v3.11.0.clusterserviceversion.yaml
Labels: approved, size/XS

#380 Update ibm-iam-operator.v3.11.0.clusterserviceversion.yaml to bump up operands
  deploy/olm-catalog/ibm-iam-operator/3.11.0/ibm-iam-operator.v3.11.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#383 Update IAM CRD versions to v1
  deploy/crds/iam.policies_v1alpha1_iampolicy.yaml
  deploy/crds/oidc_v1_client_crd.yaml
  deploy/crds/operator.ibm.com_authentications_crd.yaml
  deploy/crds/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/crds/operator.ibm.com_paps_crd.yaml
  deploy/crds/operator.ibm.com_policycontrollers_crd.yaml
  deploy/crds/operator.ibm.com_policydecisions_crd.yaml
  deploy/crds/operator.ibm.com_secretwatchers_crd.yaml
  deploy/crds/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/operator.ibm.com_securityonboardings_crd.yaml
Labels: approved, size/XXL

#384 copy crds to olm-catalog
  deploy/crds/iam.policies_v1alpha1_iampolicy.yaml
  deploy/crds/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.11.0/oidc_v1_client_crd.yaml
Labels: approved, size/L
