Repository IBM/ibm-iam-operator, pull requests merged in 2021-04, with the labels that each got.

#343 Update OWNERS - remove Srinivas from owners list
  OWNERS
Labels: approved, size/XS

#342 preserve-annotation from nss operator
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
Labels: approved, size/S

#346 Update oidcclient watcher to mount the certificates
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
Labels: approved, size/S

#349 Issue45939 - eus vulnerabilities
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, size/XS

#348 Issue45863 - vuln in operator master
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, size/XS

#339 update version for rel-3.8 fixpack.
  deploy/olm-catalog/ibm-iam-operator/3.8.3/ibm-iam-operator.v3.8.3.clusterserviceversion.yaml
Labels: approved, size/XS

#352 remove bind/escalate verbs
  deploy/olm-catalog/ibm-iam-operator/3.10.0/ibm-iam-operator.v3.10.0.clusterserviceversion.yaml
Labels: approved, size/XS

#354 Updated latest versions for operands for 2Q2021 release
  deploy/olm-catalog/ibm-iam-operator/3.10.0/ibm-iam-operator.v3.10.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/M
