Repository IBM/ibm-iam-operator, pull requests merged in 2021-05, with the labels that each got.

#357 check for saas tenant configmap and update deployment
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/deployment.go
Labels: approved, size/M

#359 return err to requeue and wait for cm creation
  pkg/controller/authentication/deployment.go
Labels: approved, size/S

#355 Changed name of namespace-admission-config webhook to support SAAS
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/webhook.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/containers.go
  pkg/controller/policydecision/containers.go
Labels: approved, size/M

#360 Update deployment.go - check nss annotations
  pkg/controller/authentication/deployment.go
Labels: approved, size/XS

#363 fix for issue 46544
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, size/XS

#364 Update Dockerfile - update Ubi images for 3.6.5
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, size/S

#361 Update ingress.go
  pkg/controller/authentication/ingress.go
Labels: approved, size/XS

#366 Code changes to skip deploying operand components if chooses not to deploy. (Issue #45713)
  deploy/crds/operator.ibm.com_policycontrollers_crd.yaml
  deploy/crds/operator.ibm.com_secretwatchers_crd.yaml
  pkg/apis/operator/v1alpha1/policycontroller_types.go
  pkg/apis/operator/v1alpha1/secretwatcher_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
Labels: approved, lgtm, size/M

#365 Code changes handle namespace-admission-config webhook resource on upgrade (Issue #46959)
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/webhook.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/M

#367 Update ibm-iam-operator.v3.10.0.clusterserviceversion.yaml
  README.md
  deploy/olm-catalog/ibm-iam-operator/3.10.0/ibm-iam-operator.v3.10.0.clusterserviceversion.yaml
Labels: approved, size/M

#368 Updated csv, crds and crs with new config parameter excludeOperand for secret-watcher and policy-controller.
  deploy/crds/operator.ibm.com_v1alpha1_pap_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_policycontroller_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_secretwatcher_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.10.0/ibm-iam-operator.v3.10.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.10.0/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.10.0/operator.ibm.com_secretwatchers_crd.yaml
  deploy/role.yaml
Labels: approved, size/M
