Repository IBM/ibm-iam-operator, pull requests merged in 2021-10, with the labels that each got.

#421 Update webhook.go
  pkg/controller/authentication/webhook.go
Labels: size/XS, approved

#424 Revert "Update webhook.go" to remove new cert annotation
  pkg/controller/authentication/webhook.go
Labels: size/XS, approved

#422 [release-k]-Update csv to use new operand image versions
  deploy/olm-catalog/ibm-iam-operator/3.12.0/ibm-iam-operator.v3.12.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#431 Update accesspolicies.go to update print statement after moving to python3
  pkg/apis/operator/v1alpha1/accesspolicies.go
Labels: size/XS, approved

#432 Issue50426-2
  pkg/apis/operator/v1alpha1/accesspolicies.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/M
