Repository IBM/ibm-iam-operator, pull requests merged in 2022-04, with the labels that each got.

#468 update from 3.17 to 3.18
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.18.0/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.18.0/ibm-iam-operator.v3.18.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.18.0/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.18.0/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.18.0/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.18.0/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.18.0/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.18.0/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.18.0/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.18.0/operator.ibm.com_securityonboardings_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL

#471 removing replaces in operator
  deploy/olm-catalog/ibm-iam-operator/3.18.0/ibm-iam-operator.v3.18.0.clusterserviceversion.yaml
Labels: size/XS

#469 do not expose loopback swagger endpoint
  pkg/controller/authentication/ingress.go
Labels: size/M

#472 movement to icr
  common/config/.hadolint.yml
  deploy/olm-catalog/ibm-iam-operator/3.18.0/ibm-iam-operator.v3.18.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: size/M
