Repository IBM/ibm-iam-operator, pull requests merged in 2022-11, with the labels that each got.

#509 Handle console url for registration json based on port 443 #55171
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/constants.go
Labels: approved, lgtm, size/S

#494 Add Okta user
  deploy/crds/operator.ibm.com_authentications_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/3.22.0/ibm-iam-operator.v3.22.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.22.0/operator.ibm.com_authentications_crd.yaml
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/secret.go
Labels: approved, lgtm, size/M

#512 version bump for 3.19.7
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.19.7/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.7/ibm-iam-operator.v3.19.7.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.7/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.7/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.7/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.7/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.7/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.7/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.7/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.7/operator.ibm.com_securityonboardings_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL

#507 [ Cloudpak 3.0 ] - Removal or CR, CRBs and webhook
  common/scripts/.githooks/make_lint-all.sh
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/clusterrole.go
  pkg/controller/authentication/clusterrolebinding.go
  pkg/controller/authentication/webhook.go
Labels: approved, size/XL, lgtm

#517 New prow cluster name
  common/Makefile.common.mk
Labels: size/XS

#518 New prow cluster name
  common/Makefile.common.mk
Labels: size/XS

#519 New prow cluster name
  common/Makefile.common.mk
Labels: size/XS, lgtm

#514 [Cloudpak 3.0] - remove CR creation, add JMX and add OSAUTH_ENABLED
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_securityonboardings_crd.yaml
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/user.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/containers.go
Labels: size/XXL, approved, lgtm
