Repository IBM/ibm-iam-operator, pull requests merged in 2022-07, with the labels that each got.

#479 Remove replace from CD3.20
  deploy/olm-catalog/ibm-iam-operator/3.20.0/ibm-iam-operator.v3.20.0.clusterserviceversion.yaml
Labels: size/XS

#481 add special flag
  deploy/crds/operator.ibm.com_authentications_crd.yaml
  deploy/crds/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/crds/operator.ibm.com_paps_crd.yaml
  deploy/crds/operator.ibm.com_policycontrollers_crd.yaml
  deploy/crds/operator.ibm.com_policydecisions_crd.yaml
  deploy/crds/operator.ibm.com_secretwatchers_crd.yaml
  deploy/crds/operator.ibm.com_securityonboardings_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.20.0/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.20.0/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.20.0/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.20.0/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.20.0/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.20.0/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.20.0/operator.ibm.com_securityonboardings_crd.yaml
Labels: approved, lgtm, size/S

#482 SCIM_AUTH_CACHE_MAX_SIZE Param - Upgrade handling
  pkg/controller/authentication/configmap.go
Labels: size/S

#483 version bump for 3.19.3 LTSR
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.19.3/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.3/ibm-iam-operator.v3.19.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.3/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.3/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.3/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.3/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.3/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.3/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.3/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.3/operator.ibm.com_securityonboardings_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL, approved, lgtm
