Repository IBM/ibm-iam-operator, pull requests merged in 2022-09, with the labels that each got.

#495 version bump for 3.19.5 ltsr
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.19.5/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.5/ibm-iam-operator.v3.19.5.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.5/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.5/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.5/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.5/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.5/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.5/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.5/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.5/operator.ibm.com_securityonboardings_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL, approved, lgtm

#496 update shared image versions
  deploy/olm-catalog/ibm-iam-operator/3.21.0/ibm-iam-operator.v3.21.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#498 Update Dockerfile
  build/Dockerfile
Labels: size/XS, approved, lgtm

#502 version bump for CD 3.22.0
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.22.0/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.22.0/ibm-iam-operator.v3.22.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.22.0/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.22.0/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.22.0/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.22.0/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.22.0/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.22.0/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.22.0/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.22.0/operator.ibm.com_securityonboardings_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL, approved, lgtm

#500 IAM onboarding resiliency (#492)
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: size/L

#501 LTSR: SCIM User API perf changes
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
Labels: approved, lgtm, size/S
