Repository IBM/ibm-iam-operator, pull requests merged in 2022-12, with the labels that each got.

#511 [ Cloudpak 3.0 ] - Add oidc v1 API
  Makefile
  deploy/crds/oidc.security.ibm.com_clients_crd.yaml
  deploy/crds/oidc_v1_client_crd.yaml
  deploy/crds/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_oidcclientwatcher_cr.yaml
  deploy/operator.yaml
  deploy/role.yaml
  go.mod
  go.sum
  pkg/api/util/conditions.go
  pkg/apis/addtoscheme_oidc_v1.go
  pkg/apis/oidc/group.go
  pkg/apis/oidc/v1/client_types.go
  pkg/apis/oidc/v1/doc.go
  pkg/apis/oidc/v1/register.go
  pkg/apis/oidc/v1/zz_generated.deepcopy.go
  pkg/apis/oidc/v1/zz_generated.openapi.go
  pkg/apis/operator/v1alpha1/oidcclientwatcher_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_client.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/secret.go
  pkg/controller/client/client_controller.go
  pkg/controller/client/clientreg.go
  pkg/controller/client/icperror.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/utils/iam.go
  pkg/utils/randomstring.go
Labels: size/XXL, approved, lgtm

#527 Cleanup watcher references and permissions after merge into IAM operator
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/role.yaml
Labels: approved, size/L, lgtm

#528 Update ibm-iam-operator.v4.0.0.clusterserviceversion.yaml to add Client permissions to ibm-iam-operator role
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#530 Add volumeMount to deployment in CSV
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
Labels: size/XS, approved, lgtm

#524 [Cloudpak 3.0 ] - Split auth pod for release-future
  OWNERS
  deploy/operator.yaml
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/ingress.go
  pkg/controller/authentication/service.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, size/XL, lgtm

#534 Remainder changes for splitting auth idp
  pkg/controller/authentication/configmap.go
Labels: size/XS, approved, lgtm
