Repository IBM/ibm-iam-operator, pull requests merged in 2023-09, with the labels that each got.

#689 Dynamic scan ltsr - headers not set
  pkg/controller/authentication/ingress.go
Labels: size/S

#690 imagePull policy update
  deploy/olm-catalog/ibm-iam-operator/3.23.7/ibm-iam-operator.v3.23.7.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/job.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/containers.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/containers.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: approved, lgtm, size/M

#691 Remove extra newline in Ingress config snippet
  pkg/controller/authentication/ingress.go
Labels: size/XS, approved

#693 update CRD description for certification
  deploy/crds/oidc.security.ibm.com_clients_crd.yaml
  deploy/crds/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.2.0/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.2.0/operator.ibm.com_authentications_crd.yaml
Labels: size/XS, approved

#692 imagePull policy update for CD
  deploy/operator.yaml
  pkg/controller/authentication/containers.go
Labels: approved, size/S

#695 Version update to 3.23.8
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.23.8/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.8/ibm-iam-operator.v3.23.8.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.8/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.8/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.8/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.8/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.8/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.8/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.8/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.8/operator.ibm.com_securityonboardings_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL, approved, lgtm

#696 Added X-Content Type Options Header
  pkg/controller/authentication/ingress.go
Labels: size/XS

#697 Add v4.3.0 CSV
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/4.3.0/ibm-iam-operator.v4.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/4.3.0/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.3.0/operator.ibm.com_authentications_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL, approved, lgtm
