Repository IBM/ibm-iam-operator, pull requests merged in 2023-07, with the labels that each got.

#659 fix for dynamic scan
  pkg/controller/authentication/ingress.go
Labels: size/XS, approved

#666 Updated go-restful to v3.8.0
  go.mod
  go.sum
Labels: size/XS, approved, lgtm

#665 Updated golang.org/x/crypto to v0.10.0
  go.mod
  go.sum
Labels: size/M

#667 Init container changes with improved probe times
  deploy/olm-catalog/ibm-iam-operator/4.1.0/ibm-iam-operator.v4.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/job.go
Labels: approved, size/M

#672 fix permission issue
  pkg/controller/authentication/constants.go
Labels: size/XS, approved, lgtm

#673 3.23.6 LTSR bump-up
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.23.6/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.6/ibm-iam-operator.v3.23.6.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.6/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.6/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.6/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.6/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.6/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.6/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.6/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.6/operator.ibm.com_securityonboardings_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL, approved

#674 Revert "fix permission issue"
  pkg/controller/authentication/constants.go
Labels: size/XS, approved

#671 Dynamic scan - set X-Content-Type-options to nosniff
  pkg/controller/authentication/ingress.go
Labels: size/XS, approved, lgtm

#669 Updated github.com/coreos/prometheus-operator version to v0.41.1
  go.mod
  go.sum
Labels: size/L
