Repository IBM/ibm-iam-operator, pull requests merged in 2023-11, with the labels that each got.

#707 Updated golang.org/x/net to v0.17.0
  go.mod
  go.sum
Labels: approved, size/S

#694 Added ca cert for provider
  pkg/controller/authentication/deployment.go
Labels: size/XS, approved, lgtm

#706 [CD]contextPool paremeters added to platform-auth-idp cm
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
Labels: approved, size/S

#708 Revert "Added ca cert for provider"
  pkg/controller/authentication/deployment.go
Labels: size/XS, approved

#709 LTSR DEC Version Bumpup
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.23.10/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.10/ibm-iam-operator.v3.23.10.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.10/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.10/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.10/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.10/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.10/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.10/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.10/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.10/operator.ibm.com_securityonboardings_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL, approved, lgtm

#712 ltsr dec end bumpup
  .gitignore
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.23.11/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.11/ibm-iam-operator.v3.23.11.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.11/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.11/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.11/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.11/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.11/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.11/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.11/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.11/operator.ibm.com_securityonboardings_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL, approved, lgtm, needs-ok-to-test

#713 Add v4.4.0 CSV
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/4.4.0/ibm-iam-operator.v4.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/4.4.0/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.4.0/operator.ibm.com_authentications_crd.yaml
  version/version.go
Labels: size/XXL, approved, lgtm

#711 Issue 60940
  pkg/controller/client/client_controller.go
Labels: approved, lgtm, size/S
