Repository IBM/ibm-iam-operator, pull requests merged in 2023-10, with the labels that each got.

#700 Version bumpup to 3.23.9[LTSR]
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.23.9/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.9/ibm-iam-operator.v3.23.9.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.9/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.9/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.9/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.9/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.9/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.9/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.9/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.9/operator.ibm.com_securityonboardings_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL, approved, lgtm

#699 ephemeral storage inclusion
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/4.3.0/ibm-iam-operator.v4.3.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/containers.go
Labels: approved, size/M

#702 Updated golang.org/x/net to v0.17.0
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#704 labels addition throguh CR
  deploy/crds/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.3.0/operator.ibm.com_authentications_crd.yaml
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/common/utils.go
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/job.go
  pkg/controller/authentication/routes.go
Labels: approved, size/L

#705 fix for multi-arch issue
  pkg/controller/authentication/constants.go
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/job.go
Labels: approved, lgtm, size/M

#703 contextPool paremeters added to platform-auth-idp cm
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
Labels: approved, lgtm, size/S
