Repository IBM/ibm-iam-operator, pull requests merged in 2023-03, with the labels that each got.

#592 Add ODLM service status to Authentications
  deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_authentications_crd.yaml
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/resourcestatus.go
Labels: approved, size/L, lgtm

#593 Set API Versions in status
  pkg/controller/authentication/resourcestatus.go
Labels: size/XS, approved, lgtm

#595 Undo audit service spec removal and add dummy data
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_authentications_crd.yaml
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/controller/authentication/authentication_controller.go
Labels: approved, size/L, lgtm

#594 Derive shared services namespace from Authentication
  pkg/apis/addtoscheme_oidc_v1.go
  pkg/controller/client/client_controller.go
  pkg/controller/client/client_controller_config.go
  pkg/controller/client/clientreg.go
  pkg/controller/client/iam.go
Labels: approved, size/L, lgtm

#596 3.19.10/3.23.2 version bump
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.23.2/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.2/ibm-iam-operator.v3.23.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.2/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.2/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.2/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.2/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.2/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.2/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.2/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.2/operator.ibm.com_securityonboardings_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL, approved

#601 Clean up CSV
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
Labels: approved, size/M

#603 Fix operator reference in CSV
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
Labels: size/XS

#599 Clean up precommit hooks and formatting
  build/Dockerfile
  build/Dockerfile.amd64
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  cmd/manager/main.go
  common/scripts/.githooks/pre-commit
  common/scripts/lint_copyright_banner.sh
  pkg/apis/addtoscheme_oidc_v1.go
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/apis/certmanager/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/oidc/v1/client_types.go
  pkg/apis/oidc/v1/zz_generated.deepcopy.go
  pkg/apis/oidc/v1/zz_generated.openapi.go
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/certificate.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/ingress.go
  pkg/controller/authentication/resourcestatus.go
  pkg/controller/authentication/routes.go
  pkg/controller/authentication/service.go
  pkg/controller/client/client_controller.go
  pkg/controller/client/client_controller_config.go
  pkg/controller/client/clientreg.go
  pkg/controller/client/iam.go
  pkg/controller/client/icperror.go
  tools.go
Labels: size/XXL, approved, lgtm

#607 Service Upgrade handling for IM4.0
  pkg/controller/authentication/service.go
Labels: approved, lgtm, size/M

#605 Upgrade handling for IM4.0
  Makefile
  go.mod
  go.sum
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/job.go
  pkg/controller/authentication/routes.go
  pkg/controller/authentication/secret.go
Labels: approved, size/L

#610 crypto ,net and sys package updated to resolve sec issue
  go.mod
  go.sum
Labels: approved, size/L, lgtm

#609 fix image build issue
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: size/XS, approved

#611 remane commonui to idp-config-ui
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
Labels: size/XS, approved, lgtm

#604 remove oauthclient and update operand SA with annotations
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/sacc.go
  pkg/controller/client/client_controller.go
Labels: approved, size/L

#591 [ Cloud Pak 3.0 IDP v3 ]Add env var in provider container
  pkg/controller/authentication/containers.go
Labels: size/XS, approved

#612 Upgrade CP2 client during CP3 upgrade
  pkg/controller/client/client_controller.go
  pkg/controller/client/client_controller_config.go
Labels: approved, lgtm, size/M

#613 Add preserve unknown fields value to status subresource
  deploy/olm-catalog/ibm-iam-operator/3.23.2/operator.ibm.com_authentications_crd.yaml
Labels: size/XS, lgtm

#615 [Cloud Pak 3.0] - SAML and OIDC HA login support
  pkg/controller/authentication/routes.go
Labels: size/XS, approved

#619 Issue 57108
  pkg/apis/apis.go
  pkg/apis/certmanager/v1alpha1/certificate_common.go
  pkg/apis/oidc/v1/client_types.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/certificate.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/ingress.go
  pkg/controller/authentication/job.go
  pkg/controller/authentication/routes.go
  pkg/controller/authentication/sacc.go
  pkg/controller/authentication/secret.go
  pkg/controller/authentication/service.go
  pkg/controller/client/conditions.go
  pkg/controller/controller.go
  version/version.go
Labels: approved, size/L, lgtm
