Repository IBM/ibm-iam-operator, pull requests merged in 2023-06, with the labels that each got.

#652 keep route certificate details
  pkg/controller/authentication/routes.go
Labels: size/XS, approved, lgtm

#657 Perform nil pointer check before dereference
  pkg/controller/authentication/routes.go
Labels: size/XS, approved, lgtm

#661 bump to 4.1.0
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/4.1.0/ibm-iam-operator.v4.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/4.1.0/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.1.0/operator.ibm.com_authentications_crd.yaml
  version/version.go
Labels: size/XXL, approved, lgtm

#656 Correct cluster address for CNCF
  pkg/controller/authentication/configmap.go
Labels: size/XS, approved

#663 Rename MongoDB to IM-MongoDB
  deploy/olm-catalog/ibm-iam-operator/4.1.0/ibm-iam-operator.v4.1.0.clusterserviceversion.yaml
Labels: size/XS, approved, lgtm

#660 fix for dynamic scan in LTSR
  pkg/controller/authentication/ingress.go
Labels: size/XS, approved

#664 create 4.0.1
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/4.0.1/ibm-iam-operator.v4.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.1/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.1/operator.ibm.com_authentications_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL, approved, lgtm
