Repository IBM/ibm-iam-operator, pull requests merged in 2023-01, with the labels that each got.

#536 enable get/list on openshift users for SCIM calls
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  pkg/controller/authentication/containers.go
Labels: approved, size/L, lgtm

#538 Issue 56423
  Makefile
  build/Dockerfile.amd64
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/apis/addtoscheme_oidc_v1.go
  pkg/controller/add_policycontroller.go
  pkg/controller/client/client_controller.go
  pkg/controller/client/client_controller_config.go
  pkg/controller/client/clientreg.go
  pkg/controller/client/iam.go
Labels: approved, size/XL, lgtm

#537 trigger build on prow that has updated go version
  README.md
Labels: size/XS, lgtm

#539 Begin phasing out use of ROKS_ENABLED for OS Auth
  pkg/controller/authentication/containers.go
  pkg/controller/client/client_controller.go
  pkg/controller/client/client_controller_config.go
Labels: approved, size/M

#529 Port back OKTA changes
  deploy/crds/operator.ibm.com_authentications_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_authentications_crd.yaml
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/secret.go
Labels: approved, size/M

#540 [Cloudpak 3.0] Made changes to support multiple namespace
  cmd/manager/main.go
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#545 version bump for 3.19.8
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.19.8/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.8/ibm-iam-operator.v3.19.8.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.8/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.8/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.8/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.8/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.8/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.8/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.8/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.19.8/operator.ibm.com_securityonboardings_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL

#546 Added sigs.k8s.io/controller-runtime/pkg/cache package
  cmd/manager/main.go
Labels: size/XS, approved, lgtm

#548 Update artifactory - Release LTSR
  Makefile
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  common/config/.hadolint.yml
  common/scripts/config_docker.sh
Labels: approved, size/S

#550 Update artifactory - Release Future
  Makefile
  build/Dockerfile
  build/Dockerfile.amd64
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  common/config/.hadolint.yml
  common/scripts/config_docker.sh
Labels: approved, size/S

#543 Enable cpclient_credentials grant type
  Makefile
  pkg/apis/oidc/v1/client_types.go
  pkg/controller/client/client_controller.go
  pkg/controller/client/client_controller_config.go
  pkg/controller/client/clientreg.go
  pkg/controller/client/iam.go
  pkg/controller/client/icperror.go
Labels: size/XXL, approved, lgtm

#547 Update ibm-iam-operator.v4.0.0.clusterserviceversion.yaml to read from namespace scope
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
Labels: size/XS, approved, lgtm

#551 Amend cpclient credentials
  pkg/apis/oidc/v1/client_types.go
  pkg/controller/client/client_controller.go
  pkg/controller/client/clientreg.go
Labels: approved, size/S

#541 removal of PAP,PDP and token service
  deploy/crds/iam.policies_v1alpha1_iampolicy.yaml
  deploy/crds/operator.ibm.com_paps_crd.yaml
  deploy/crds/operator.ibm.com_policycontrollers_crd.yaml
  deploy/crds/operator.ibm.com_policydecisions_crd.yaml
  deploy/crds/operator.ibm.com_secretwatchers_crd.yaml
  deploy/crds/operator.ibm.com_securityonboardings_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_pap_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_policycontroller_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_policydecision_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_secretwatcher_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_securityonboarding_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_securityonboardings_crd.yaml
  pkg/controller/add_pap.go
  pkg/controller/add_policydecision.go
  pkg/controller/add_secretwatcher.go
  pkg/controller/add_securityonboarding.go
  pkg/controller/authentication/constants.go
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/ingress.go
Labels: size/XXL, approved, lgtm

#555 Update ibm-iam-operator.v4.0.0.clusterserviceversion.yaml to add the ingress dependencies
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
Labels: size/XS, approved, lgtm

#557 Update config_docker.sh- remove 2nd docker login
  common/scripts/config_docker.sh
Labels: size/XS, approved

#558 Fix saml login, remove token service ingress
  pkg/controller/authentication/ingress.go
Labels: approved, size/L

#561 Update ibm-iam-operator.v4.0.0.clusterserviceversion.yaml to remove cert-manager dependency
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
Labels: size/XS, approved

#560 [CP 3.0] - Update ibm-iam-operator.v4.0.0.clusterserviceversion.yaml to add label
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
Labels: size/XS, approved

#562 osauth:update SA with annotation
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/sacc.go
  pkg/resources/utils.go
Labels: approved, size/L

#564 remove userbuilder
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/apis/operator/v1alpha1/register.go
  pkg/controller/authentication/authentication_controller.go
Labels: approved, size/L
