Repository IBM/ibm-iam-operator, pull requests merged in 2023-02, with the labels that each got.

#542 Ingress removal from IM
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/certificate.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/constants.go
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/ingress.go
  pkg/controller/authentication/job.go
  pkg/controller/authentication/secret.go
Labels: size/XXL, approved, lgtm

#565 [ Cloud Pak 3.0] - Move certificates from v1alpha1 to v1
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
  deploy/role.yaml
  go.mod
  go.sum
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/controller/authentication/certificate.go
  pkg/controller/authentication/containers.go
Labels: approved, size/XL

#556 Remove PAP,PDP, onboarding controllers and types
  pkg/apis/operator/v1alpha1/accesspolicies.go
  pkg/apis/operator/v1alpha1/pap_types.go
  pkg/apis/operator/v1alpha1/policycontroller_types.go
  pkg/apis/operator/v1alpha1/policydecision_types.go
  pkg/apis/operator/v1alpha1/secretwatcher_types.go
  pkg/apis/operator/v1alpha1/securityonboarding_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/pap/containers.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/containers.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: size/XXL, approved

#566 Replace Ingresses with Routes
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/certificate.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/deployment.go
  pkg/controller/authentication/ingress.go
  pkg/controller/authentication/job.go
  pkg/controller/authentication/routes.go
  pkg/controller/authentication/secret.go
  pkg/controller/authentication/service.go
  pkg/controller/client/clientreg.go
Labels: size/XXL, approved

#567 move route permissions to IAM operator SA
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
Labels: approved, size/M

#570 [CP3.0] - Update authentication_controller.go to fix calls to v1alpha certs
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/certificate.go
Labels: size/XS, approved, lgtm

#572 Remove router-certs from auth deployment
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/deployment.go
Labels: approved, lgtm, size/S

#574 Update routes
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/routes.go
Labels: approved, size/M

#576 Add route for social login
  pkg/controller/authentication/routes.go
Labels: approved, lgtm, size/S

#577 Update routes.go to fix idmgmt
  pkg/controller/authentication/routes.go
Labels: size/XS, approved, lgtm

#573 provider and management pods to check for auth-service readiness
  pkg/controller/authentication/containers.go
Labels: approved, size/S

#580 sod changes
  Makefile
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/clusterrole.go
  pkg/controller/authentication/clusterrolebinding.go
  pkg/controller/authentication/sacc.go
Labels: approved, size/XL, lgtm

#581 Add nil checks to IsRouteEqual logging
  pkg/controller/authentication/routes.go
Labels: approved, lgtm, size/M

#582 fix twistlock issues
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#583 Issue57138 to fix saml metadata download
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/controller/authentication/certificate.go
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/deployment.go
Labels: approved, size/M

#585 Issue 56869
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  pkg/controller/client/client_controller.go
  pkg/controller/client/client_controller_config.go
  pkg/controller/client/clientreg.go
  pkg/controller/client/conditions.go
  pkg/controller/client/iam.go
  pkg/controller/client/icperror.go
Labels: approved, size/XL, lgtm
