Repository IBM/ibm-iam-operator, pull requests merged in 2023-04, with the labels that each got.

#621 manager&provider initcontainers to check for IBMJMXConnectorREST availability
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/deployment.go
Labels: approved, size/M

#623 version bump for next ltsr(3.19.11/3.23.3)
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.23.3/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.3/ibm-iam-operator.v3.23.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.3/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.3/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.3/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.3/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.3/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.3/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.3/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.3/operator.ibm.com_securityonboardings_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL

#624 Remove dependency on Routes API
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/apis/utils.go
  pkg/common/constants.go
  pkg/common/utils.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/resourcestatus.go
  pkg/controller/authentication/routes.go
  pkg/controller/authentication/sacc.go
  pkg/controller/authentication/secret.go
  pkg/controller/client/client_controller.go
  pkg/controller/client/clientreg.go
  pkg/controller/client/iam.go
  pkg/controller/common/randomstring.go
  pkg/controller/common/resources.go
Labels: approved, size/XL, lgtm

#622 zenAuditUrl inclusion to zenInstance collection
  pkg/controller/client/clientreg.go
Labels: size/XS, approved

#626 Set Duration on Certificates and displayName for im-operator
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
  pkg/controller/authentication/certificate.go
Labels: size/XS, approved, lgtm

#628 Changed IAM to IM in description and summary
  build/Dockerfile
  build/Dockerfile.amd64
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/S

#627 Trigger build on prow that has updated go version
  README.md
Labels: size/XS, approved, lgtm

#620 cleanup OSAuthEnabled/OSAUTH_ENABLED due to idpv3
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
  pkg/controller/authentication/service.go
  pkg/controller/client/client_controller.go
  pkg/controller/client/client_controller_config.go
Labels: approved, lgtm, size/M

#630 fix SA update for clients
  pkg/controller/authentication/sacc.go
  pkg/controller/client/client_controller.go
  pkg/controller/common/resources.go
Labels: approved, size/M

#634 Fix registered API detection
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/apis/utils.go
  pkg/controller/client/clientreg.go
Labels: approved, lgtm, size/M

#631 cleanup osAuthEnabled/OSAUTH_ENABLED in-place of idpv3
  deploy/crds/operator.ibm.com_v1alpha1_authentication_cr.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
  pkg/apis/operator/v1alpha1/authentication_types.go
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/containers.go
  pkg/controller/client/client_controller.go
  pkg/controller/client/client_controller_config.go
Labels: approved, lgtm, size/M

#637 Update containers.go to remove JMX API check
  pkg/controller/authentication/containers.go
Labels: size/XS, approved
