Repository IBM/ibm-iam-operator, pull requests merged in 2023-08, with the labels that each got.

#675 dynamic scan - x-content-type header set to nosniff
  pkg/controller/authentication/ingress.go
Labels: size/XS

#678 version bump for CS 4.2.0
  Makefile
  deploy/olm-catalog/ibm-iam-operator/4.2.0/ibm-iam-operator.v4.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/4.2.0/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/4.2.0/operator.ibm.com_authentications_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL, approved, lgtm

#679 ltsr(sept) version update
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.23.7/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.7/ibm-iam-operator.v3.23.7.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.7/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.7/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.7/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.7/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.7/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.7/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.7/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.7/operator.ibm.com_securityonboardings_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL

#677 Updated client-go version to 0.27.2
  go.mod
  go.sum
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/containers.go
  pkg/controller/oidcclientwatcher/oidcclientwatcher_controller.go
  pkg/controller/pap/containers.go
  pkg/controller/pap/pap_controller.go
  pkg/controller/policycontroller/policycontroller_controller.go
  pkg/controller/policydecision/containers.go
  pkg/controller/policydecision/policydecision_controller.go
  pkg/controller/secretwatcher/secretwatcher_controller.go
  pkg/controller/securityonboarding/securityonboarding_controller.go
Labels: size/XXL

#670 Dynamic scan- Set header X-Content-Type-options to nosniff
  pkg/controller/authentication/ingress.go
Labels: size/XS, approved, lgtm

#682 Updated github.com/emicklei/go-restful/v3 to v3.10.0
  go.mod
  go.sum
Labels: size/XS

#683 Updated github.com/emicklei/go-restful/v3 to v3.10.0
  go.mod
  go.sum
Labels: size/XS

#687 Updated go-restful v3.11.0
  go.mod
  go.sum
Labels: approved, lgtm, size/S
