Repository IBM/ibm-iam-operator, pull requests merged in 2023-05, with the labels that each got.

#640 Simplify Client reconciler cert usage
  pkg/controller/client/client_controller.go
  pkg/controller/client/clientreg.go
Labels: approved, size/M

#641 Remove exit on failure for missing schemes
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/apis/utils.go
Labels: approved, lgtm, size/S

#638 Remove `state` parameter from platform-login Route
  pkg/controller/authentication/routes.go
Labels: size/XS, approved

#643 update https for cluster ep
  pkg/controller/authentication/configmap.go
Labels: size/XS, approved, lgtm

#648 fix issues in wildcard removal
  deploy/olm-catalog/ibm-iam-operator/4.0.0/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/4.0.0/operator.ibm.com_policydecisions_crd.yaml
  deploy/role.yaml
Labels: approved, size/L, lgtm

#649 Update ImagePullPolicy to IfNotPresent
  deploy/olm-catalog/ibm-iam-operator/4.0.0/ibm-iam-operator.v4.0.0.clusterserviceversion.yaml
Labels: size/XS, approved, lgtm

#650 Update registration-json to reconcile regularly
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/constants.go
Labels: approved, size/L, lgtm

#644 Updated golang-jwt to v4.4.3
  go.mod
  go.sum
Labels: size/XS, approved, lgtm

#645 Updated golang net to 0.7.0
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#651 Fix ownership of ibmcloud-* resources issues
  pkg/controller/authentication/authentication_controller.go
  pkg/controller/authentication/configmap.go
  pkg/controller/authentication/job.go
  pkg/controller/authentication/resourcestatus.go
  pkg/controller/authentication/secret.go
  pkg/controller/client/client_controller.go
  pkg/controller/client/clientreg.go
  pkg/controller/common/resources.go
Labels: approved, size/L
