Repository IBM/ibm-iam-operator, pull requests merged in 2024-04, with the labels that each got.

#797 Scim Jit Data Migration
  migration/migration.go
  migration/schema/v1/tables.go
Labels: approved, size/L, lgtm

#790 62803: Add DB_CONNECT_MAX_RETRIES env variable
  controllers/operator/configmap.go
  controllers/operator/containers.go
Labels: size/XS, approved, lgtm, needs-ok-to-test

#798 Populate realm_id in users table - mongo Users.directoryId to pgsql Users.realm_id
  migration/schema/v1/tables.go
Labels: size/XS, approved

#799 Fetching "uid" of user based on "realm_id" OR "type" column
  migration/schema/v1/tables.go
Labels: size/XS, approved, lgtm

#800 move code block upper for saml realm_id
  migration/schema/v1/tables.go
Labels: size/XS, approved

#801 Migration now fail safe if user_uid is null
  migration/migration.go
Labels: approved, lgtm, size/S

#803 add bindinfoRefresh labels and annotations
  controllers/operator/deployment.go
Labels: approved, size/M

#806 Update to version 4.6
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  config/manager/overlays/prod/image_env_vars_patch.yaml
  config/manager/overlays/prod/kustomization.yaml
  config/manifests/overlays/prod/annotations_patch.yaml
  config/samples/overlays/prod/authentication_image_patch.yaml
  hack/relatedimages.yaml
  version/version.go
Labels: approved, lgtm, size/M, needs-ok-to-test

#807 Update to version 4.5.1
  DEVELOPMENT.md
  README.md
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/overlays/prod/image_env_vars_patch.yaml
  config/manager/overlays/prod/kustomization.yaml
  config/manifests/overlays/prod/annotations_patch.yaml
  config/samples/overlays/prod/authentication_image_patch.yaml
  hack/relatedimages.yaml
  version/version.go
Labels: approved, lgtm, size/M, needs-ok-to-test

#808 updating files v4.6
  DEVELOPMENT.md
  README.md
  common/scripts/multiarch_image.sh
Labels: size/XS, approved, lgtm, needs-ok-to-test

#809 Refactoring memory utilisation
  controllers/operator/containers.go
Labels: size/XS, approved, lgtm, needs-ok-to-test

#810 Refactoring memory utilisation
  controllers/operator/containers.go
Labels: size/XS, approved, lgtm, needs-ok-to-test

#812 Updated golang.org/x/net to v0.23.0
  go.mod
  go.sum
Labels: approved, lgtm, size/S, security-fix

#811 Add support for configuring iam APIs behind the zen front door
  apis/operator/v1alpha1/authentication_types.go
  apis/operator/v1alpha1/zz_generated.deepcopy.go
  apis/zen.cpd.ibm.com/v1/groupversion_info.go
  apis/zen.cpd.ibm.com/v1/zenextension_types.go
  apis/zen.cpd.ibm.com/v1/zz_generated.deepcopy.go
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_authentications.yaml
  config/rbac/role.yaml
  controllers/common/utils.go
  controllers/operator/authentication_controller.go
  controllers/operator/deployment.go
  controllers/operator/routes.go
  controllers/operator/zenextension.go
  main.go
Labels: approved, size/XL

#813 Namespaced migration keys sc2
  controllers/operator/authentication_controller.go
  migration/migration.go
  migration/options.go
Labels: approved, size/L, lgtm
