Repository IBM/ibm-iam-operator, pull requests merged in 2024-02, with the labels that each got.

#743 3.23.13 ltsr version bump
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.23.13/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.13/ibm-iam-operator.v3.23.13.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.13/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.13/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.13/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.13/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.13/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.13/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.13/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.13/operator.ibm.com_securityonboardings_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL, approved, lgtm

#745 Issue 62159
  Makefile
  apis/operator/v1alpha1/authentication_types.go
  apis/operator/v1alpha1/operandrequest_types.go
  apis/operator/v1alpha1/zz_generated.deepcopy.go
  build/Dockerfile.amd64
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  bundle.Dockerfile
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/rbac/role.yaml
  controllers/common/constants.go
  controllers/operator/authentication_controller.go
  controllers/operator/containers.go
  controllers/operator/deployment.go
  controllers/operator/migration/migration.go
  controllers/operator/operandrequest.go
  controllers/operator/operandrequest_test.go
  go.mod
Labels: size/XXL, approved, lgtm

#747 fix build issue
  Makefile
Labels: size/XS, approved

#748 Add initialization of EDB schemas
  Makefile
  common/scripts/multiarch_image.sh
  controllers/operator/authentication_controller.go
  controllers/operator/migration/migration.go
  controllers/operator/migration/v1.sql
  go.mod
  go.sum
Labels: approved, size/XL

#751 Disable DDL execution until Operands are updated
  controllers/operator/authentication_controller.go
Labels: approved, size/M

#749 db connection parameters
  controllers/operator/configmap.go
  controllers/operator/containers.go
Labels: approved, lgtm, size/S
