Repository IBM/ibm-iam-operator, pull requests merged in 2024-11, with the labels that each got.

#906 Update zenextension.go to add proxy buffers
  controllers/operator/zenextension.go
Labels: approved, lgtm, size/S

#903 Issue 65211 cd
  apis/operator/v1alpha1/authentication_types.go
  controllers/operator/authentication_controller.go
  controllers/operator/authentication_controller_test.go
  controllers/operator/operandrequest.go
  controllers/operator/operandrequest_test.go
  controllers/operator/resourcestatus.go
  database/migrate.go
  database/schema/v1/migrations.go
Labels: approved, size/XL, lgtm

#907 [CD]fix for bindinfoRefresh
  controllers/common/utils.go
  controllers/operator/deployment.go
Labels: approved, size/M

#909 Add catalog building
  .gitignore
  DEVELOPMENT.md
  Makefile
  common/scripts/multiarch_image.sh
  hack/bundle-render
  hack/channel-render
Labels: approved, size/L

#908 4.6.9 sc2 bumpup
  DEVELOPMENT.md
  README.md
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/overlays/prod/image_env_vars_patch.yaml
  config/manager/overlays/prod/kustomization.yaml
  config/manifests/overlays/prod/annotations_patch.yaml
  config/samples/overlays/prod/authentication_image_patch.yaml
  hack/relatedimages.yaml
  version/version.go
Labels: approved, size/M

#910 Run migrations dynamically
  Makefile
  apis/oidc.security/v1/zz_generated.deepcopy.go
  apis/operator/v1alpha1/authentication_types.go
  apis/operator/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  controllers/common/resources.go
  controllers/operator/authentication_controller.go
  controllers/operator/authentication_controller_test.go
  controllers/operator/certificate.go
  controllers/operator/routes.go
  database/connectors/dbconn.go
  database/connectors/options.go
  database/migrate.go
  database/migration/migration.go
  database/migration/migration_test.go
  database/schema/v1/dbinit.sql
  database/schema/v1/migration_test.go
  database/schema/v1/migrations.go
  database/schema/v1/mongotoedb.go
  database/schema/v1/suite_test.go
  database/schema/v1/tables.go
  database/schema/v1/tables_test.go
  database/schema/v1/version.go
  go.mod
  go.sum
  migration/migration_test.go
Labels: size/XXL, approved, lgtm

#912 Reconcile Routes and ZenExtension later
  controllers/operator/authentication_controller.go
Labels: approved, lgtm, size/S

#911 [SC2]fix for bindinfoRefresh
  controllers/common/utils.go
  controllers/operator/deployment.go
Labels: approved, size/M

#914 Remove migration replay behavior
  apis/operator/v1alpha1/authentication_types.go
  controllers/operator/authentication_controller.go
  controllers/operator/authentication_controller_test.go
  controllers/operator/operandrequest.go
  controllers/operator/operandrequest_test.go
  controllers/operator/resourcestatus.go
  database/migrate.go
  database/schema/v1/migrations.go
Labels: approved, size/XL, lgtm
