Repository IBM/ibm-iam-operator, pull requests merged in 2024-06, with the labels that each got.

#837 keep default mode as require
  controllers/operator/configmap.go
Labels: approved

#835 [SC2]shutdown mongo on successful migration
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  config/manager/bases/manager.yaml
  controllers/common/constants.go
  controllers/operator/authentication_controller.go
Labels: approved, size/M

#840 Update to version 4.7.0
  DEVELOPMENT.md
  README.md
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/overlays/prod/image_env_vars_patch.yaml
  config/manager/overlays/prod/kustomization.yaml
  config/manifests/overlays/prod/annotations_patch.yaml
  config/samples/overlays/prod/authentication_image_patch.yaml
  hack/relatedimages.yaml
  version/version.go
Labels: approved, lgtm, size/M, needs-ok-to-test

#841 [SC2] Fix for Issue #63800: In-place upgrade from LTSR to 4.6.3 causing AuthenticationCR as NotReady
  controllers/operator/authentication_controller.go
Labels: size/M

#842 Updated golang.org/x/net v0.23.0 & google.golang.org/protobuf v1.33.0
  go.mod
  go.sum
Labels: size/S

#843 Update to v4.5.3
  DEVELOPMENT.md
  README.md
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/overlays/prod/image_env_vars_patch.yaml
  config/manager/overlays/prod/kustomization.yaml
  config/manifests/overlays/prod/annotations_patch.yaml
  config/samples/overlays/prod/authentication_image_patch.yaml
  hack/relatedimages.yaml
  version/version.go
Labels: approved, lgtm, size/M, needs-ok-to-test
