Repository IBM/ibm-iam-operator, pull requests merged in 2024-03, with the labels that each got.

#755 Copy data from MongoDB to EDB
  .gitignore
  Makefile
  apis/operator/v1alpha1/authentication_types.go
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/default/overlays/dev/kustomization.yaml
  config/manager/overlays/dev/image_env_vars_patch.yaml
  config/manager/overlays/dev/kustomization.yaml
  config/manifests/overlays/dev/annotations_patch.yaml
  config/manifests/overlays/dev/kustomization.yaml
  config/rbac/kustomization.yaml
  config/samples/overlays/dev/authentication_image_patch.yaml
  config/samples/overlays/dev/kustomization.yaml
  controllers/operator/authentication_controller.go
  controllers/operator/authentication_controller_test.go
  controllers/operator/migration/migration.go
  controllers/operator/migration/migration_test.go
  controllers/operator/migration/options.go
  controllers/operator/migration/schema/v1/tables.go
  controllers/operator/migration/v1.sql
  controllers/operator/operandrequest_test.go
  go.mod
  go.sum
  hack/create_dev_overlays
  hack/external-crs.json
  hack/patch-built-bundle
Labels: size/XXL, approved

#756 init container to support external db check
  controllers/operator/containers.go
Labels: approved, size/M

#757 Remove unused leader election rbac
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  bundle/manifests/leader-election-role_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/leader-election-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
Labels: approved, lgtm, size/M

#758 Add timeout to HTTP requests
  controllers/oidc.security/iam.go
  controllers/oidc.security/zen_registration.go
Labels: approved, size/S

#759 Catch IsNotFound error instead of ignoring
  controllers/operator/authentication_controller.go
Labels: size/XS, approved

#762 Add a common label for CPFS Operator Pods
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  config/manager/bases/manager.yaml
Labels: approved, size/S

#763 scimattr schema change
  controllers/operator/migration/v1.sql
Labels: size/XS, lgtm

#764 Add DEVELOPMENT.md
  DEVELOPMENT.md
  README.md
Labels: approved, size/L, lgtm

#765 zen_instances_users table column uz_id changed to uid
  controllers/operator/migration/migration.go
  controllers/operator/migration/schema/v1/tables.go
  controllers/operator/migration/v1.sql
Labels: approved, size/S

#768 Retain MongoDB if annotation is set on Auth CR
  apis/operator/v1alpha1/authentication_types.go
  controllers/operator/operandrequest.go
Labels: approved, lgtm, size/S

#767 idp_configs: change ldap_config(json) to ldap_id(string)
  controllers/operator/migration/migration.go
  controllers/operator/migration/schema/v1/tables.go
  controllers/operator/migration/v1.sql
Labels: approved, size/S

#774 Revert "mongo cleanup"
  apis/operator/v1alpha1/authentication_types.go
  controllers/operator/configmap.go
  controllers/operator/containers.go
  controllers/operator/deployment.go
  controllers/operator/job.go
  controllers/operator/operandrequest.go
Labels: approved, size/L

#760 Add delays to Authentication requeues
  controllers/operator/authentication_controller.go
  controllers/operator/operandrequest.go
Labels: approved, lgtm, size/M

#772 add missing envs to provider/management pods
  controllers/operator/containers.go
Labels: size/XS, approved

#770 Add V2 Directory migration
  controllers/operator/migration/migration.go
  controllers/operator/migration/schema/v1/tables.go
  controllers/operator/migration/schema/v1/tables_test.go
Labels: approved, size/XL

#771 Remove MongoDB resources when retain is false
  Makefile
  apis/operator/v1alpha1/authentication_types.go
  controllers/operator/authentication_controller.go
  controllers/operator/operandrequest.go
  controllers/operator/operandrequest_test.go
Labels: approved, size/XL

#779 Clean up mongo
  controllers/operator/configmap.go
  controllers/operator/containers.go
  controllers/operator/deployment.go
  controllers/operator/job.go
Labels: approved, size/L

#769 Update schemas
  controllers/operator/authentication_controller.go
  controllers/operator/authentication_controller_test.go
  migration/migration.go
  migration/migration_test.go
  migration/options.go
  migration/schema/v1/dbinit.sql
  migration/schema/v1/tables.go
  migration/schema/v1/tables_test.go
Labels: approved, size/XL

#780 last_login column removal from users table
  migration/schema/v1/dbinit.sql
  migration/schema/v1/tables.go
Labels: approved, size/M

#781 assign directory's _id to uid
  migration/schema/v1/tables.go
  migration/schema/v1/tables_test.go
Labels: approved, lgtm, size/S

#782 Add handling for mongodb-preload-endpoint
  controllers/operator/authentication_controller.go
  migration/migration.go
Labels: approved, size/L, lgtm

#783 Set Zen instance client secret if not set
  migration/migration.go
  migration/migration_test.go
  migration/schema/v1/tables.go
Labels: approved, size/L, lgtm

#786 Create VIEWs for scim_server custom tables
  migration/schema/v1/dbinit.sql
Labels: approved, lgtm, size/S

#789 ON DELETE CASCADE for user_preferences
  migration/schema/v1/dbinit.sql
Labels: size/XS, approved

#791 go version updated to 1.21.8
  Dockerfile
Labels: size/XS, approved

#788 ON DELETE CASCADE for users_groups
  migration/schema/v1/dbinit.sql
Labels: size/XS, approved, lgtm

#794 Update Go 1.21.7 -> 1.21.8
  Makefile
Labels: size/XS, approved, lgtm

#784 Update Non Zen User roles for isolated upgrade
  migration/migration.go
  migration/schema/v1/tables.go
  migration/schema/v1/tables_test.go
Labels: approved, size/L, lgtm

#785 Check for Deployments before registering Clients
  controllers/common/constants.go
  controllers/oidc.security/client_controller.go
Labels: approved, size/XL, lgtm

#793 Create unique ClusterRoleBindings
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  controllers/operator/authentication_controller.go
  controllers/operator/clusterrolebinding.go
Labels: approved, lgtm, size/M

#792 Add MigrationsPerformed condition
  apis/operator/v1alpha1/authentication_types.go
  controllers/operator/authentication_controller.go
  controllers/operator/resourcestatus.go
  migration/migration.go
Labels: approved, lgtm, size/M

#795 scimserver migration
  migration/migration.go
  migration/schema/v1/tables.go
Labels: approved, size/XL, lgtm
