Repository IBM/ibm-iam-operator, pull requests merged in 2024-08, with the labels that each got.

#859 Update to v4.5.5
  DEVELOPMENT.md
  README.md
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/overlays/prod/image_env_vars_patch.yaml
  config/manager/overlays/prod/kustomization.yaml
  config/manifests/overlays/prod/annotations_patch.yaml
  config/samples/overlays/prod/authentication_image_patch.yaml
  hack/relatedimages.yaml
  version/version.go
Labels: approved, lgtm, size/M, needs-ok-to-test

#861 Updated to ubi9 [SC2]
  Dockerfile
  build/Dockerfile.amd64
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: size/S

#863 increment qemu version
  build/Dockerfile.ppc64le
Labels: size/XS, approved

#864 fix s390x build issue - increment qemu version
  build/Dockerfile.s390x
Labels: size/XS, approved

#860 Adding securityContext field
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  config/manager/bases/manager.yaml
  controllers/operator/containers.go
  controllers/operator/deployment.go
  controllers/operator/job.go
Labels: approved, lgtm, size/M, needs-ok-to-test

#862 Updated to ubi9 [CD]
  Dockerfile
  build/Dockerfile.amd64
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/S

#868 use cert apis from ibm cert mgr operator
  controllers/operator/authentication_controller.go
  controllers/operator/certificate.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/S

#854 Fix bundle builds
  bundle.Dockerfile
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_authentications.yaml
  config/rbac/role.yaml
  config/samples/bases/operator_v1alpha1_authentication.yaml
  hack/relatedimages.yaml
  hack/update_image_refs
Labels: approved, size/S
