Repository IBM/ibm-iam-operator, pull requests merged in 2024-12, with the labels that each got.

#915 Update to version 4.10
  DEVELOPMENT.md
  README.md
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/overlays/prod/image_env_vars_patch.yaml
  config/manager/overlays/prod/kustomization.yaml
  config/manifests/overlays/prod/annotations_patch.yaml
  config/samples/overlays/prod/authentication_image_patch.yaml
  database/schema/v1/tables_test.go
  hack/relatedimages.yaml
  version/version.go
Labels: approved, lgtm, size/M

#917 version upgrade 4.6.10-sc2
  DEVELOPMENT.md
  README.md
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/overlays/prod/image_env_vars_patch.yaml
  config/manager/overlays/prod/kustomization.yaml
  config/manifests/overlays/prod/annotations_patch.yaml
  config/samples/overlays/prod/authentication_image_patch.yaml
  hack/relatedimages.yaml
  version/version.go
Labels: approved, lgtm, size/M

#916 Set InsecureSkipVerify to false[CD]
  config/prometheus/monitor.yaml
  database/connectors/options.go
Labels: size/XS, approved

#904 [CD]Align ibmcloud-cluster-info CM fields to zen front door host
  controllers/operator/zenextension.go
Labels: size/XS, approved

#918 65104: Add DEFAULT_LOGIN in platform-auth-idp configMap
  apis/operator/v1alpha1/authentication_types.go
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_authentications.yaml
  config/crd/bases/operator.ibm.com_authentications.yaml
  config/samples/bases/operator_v1alpha1_authentication.yaml
  controllers/operator/configmap.go
  controllers/operator/containers.go
Labels: approved, lgtm, size/S, needs-ok-to-test

#921 Always update ROKS_URL in platform-auth-idp
  apis/operator/v1alpha1/authentication_types.go
  controllers/common/constants.go
  controllers/operator/authentication_controller.go
  controllers/operator/configmap.go
  controllers/operator/configmap_test.go
Labels: size/XXL, approved
