Repository IBM/ibm-iam-operator, pull requests merged in 2024-05, with the labels that each got.

#814 Setting OwnerReference
  controllers/operator/operandrequest.go
Labels: size/XS, approved, lgtm, needs-ok-to-test

#819 Issue-63377: Migrating tokens to EDB
  migration/migration.go
  migration/schema/v1/tables.go
Labels: approved, size/L, lgtm

#820 Issue-63379: Fix for nil pointer error if user has already been migrated
  migration/migration.go
Labels: size/XS, approved, lgtm

#821 add zenFrontDoor flag to alm examples
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
Labels: size/XS, approved, lgtm

#822 Setting OwnerReference
  controllers/operator/operandrequest.go
Labels: size/XS, approved, lgtm, needs-ok-to-test

#824 LTSR June 3.23.14 version update
  Makefile
  common/scripts/lint-csv.sh
  deploy/olm-catalog/ibm-iam-operator/3.23.14/iam.policies_v1alpha1_iampolicy.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.14/ibm-iam-operator.v3.23.14.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.14/oidc_v1_client_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.14/operator.ibm.com_authentications_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.14/operator.ibm.com_oidcclientwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.14/operator.ibm.com_paps_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.14/operator.ibm.com_policycontrollers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.14/operator.ibm.com_policydecisions_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.14/operator.ibm.com_secretwatchers_crd.yaml
  deploy/olm-catalog/ibm-iam-operator/3.23.14/operator.ibm.com_securityonboardings_crd.yaml
  deploy/operator.yaml
  version/version.go
Labels: size/XXL, approved, lgtm

#826 set endpoint address from cluster address on eks
  controllers/operator/configmap.go
Labels: size/XS, lgtm

#825 set endpoint address from cluster address on eks [ DONT MERGE - track 63424 ]
  controllers/operator/configmap.go
Labels: size/XS, approved

#827 [CD]introduced DB_SSL_MODE
  controllers/operator/configmap.go
  controllers/operator/containers.go
Labels: approved, size/S

#828 [CD] Update zen-instance for client CR update
  controllers/oidc.security/client_controller.go
Labels: approved, lgtm, size/S

#830 [CD]Namespaced migration keys
  controllers/operator/authentication_controller.go
  migration/migration.go
  migration/options.go
Labels: approved, size/L

#831 [CD]Migrating tokens to EDB
  migration/migration.go
  migration/schema/v1/tables.go
Labels: approved, size/L, lgtm

#834 Update to version 4.5.2
  DEVELOPMENT.md
  README.md
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/overlays/prod/image_env_vars_patch.yaml
  config/manager/overlays/prod/kustomization.yaml
  config/manifests/overlays/prod/annotations_patch.yaml
  config/samples/overlays/prod/authentication_image_patch.yaml
  hack/relatedimages.yaml
  version/version.go
Labels: approved, lgtm, size/M, needs-ok-to-test

#829 [SC2] Update zen-instance for client CR update
  controllers/oidc.security/client_controller.go
Labels: approved, lgtm, size/S

#817 [SC2]introduced DB_SSL_MODE
  controllers/operator/configmap.go
  controllers/operator/containers.go
Labels: approved, size/S
