Repository IBM/ibm-iam-operator, pull requests merged in 2024-07, with the labels that each got.

#845 ensure roks_url is correct
  controllers/operator/configmap.go
Labels: size/XS, approved, lgtm

#847 [CD]ensure roks_url is correct
  controllers/operator/configmap.go
Labels: size/XS, approved, lgtm

#844 [CD]shutdown mongo on successful migration
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  config/manager/bases/manager.yaml
  controllers/common/constants.go
  controllers/operator/authentication_controller.go
Labels: approved, size/M

#855 Update to V4.5.4
  DEVELOPMENT.md
  README.md
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/overlays/prod/image_env_vars_patch.yaml
  config/manager/overlays/prod/kustomization.yaml
  config/manifests/overlays/prod/annotations_patch.yaml
  config/samples/overlays/prod/authentication_image_patch.yaml
  hack/relatedimages.yaml
  version/version.go
Labels: approved, lgtm, size/M, needs-ok-to-test

#856 Update to v4.8.0
  DEVELOPMENT.md
  README.md
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/overlays/prod/image_env_vars_patch.yaml
  config/manager/overlays/prod/kustomization.yaml
  config/manifests/overlays/prod/annotations_patch.yaml
  config/samples/overlays/prod/authentication_image_patch.yaml
  hack/relatedimages.yaml
  version/version.go
Labels: approved, lgtm, size/M, needs-ok-to-test

#858 Update go version from 1.21.8 to 1.21.12
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm, needs-ok-to-test
