Repository IBM/ibm-iam-operator, pull requests merged in 2024-10, with the labels that each got.

#893 instana-agent enablement
  apis/operator/v1alpha1/authentication_types.go
  bundle/manifests/operator.ibm.com_authentications.yaml
  config/crd/bases/operator.ibm.com_authentications.yaml
  controllers/operator/containers.go
Labels: approved, lgtm, size/M

#894 introduce INSTANA_AGENT_ENABLED env
  controllers/operator/containers.go
Labels: approved, lgtm, size/M

#896 Bump version to 4.5.7
  DEVELOPMENT.md
  README.md
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/overlays/prod/image_env_vars_patch.yaml
  config/manager/overlays/prod/kustomization.yaml
  config/manifests/overlays/prod/annotations_patch.yaml
  config/samples/overlays/prod/authentication_image_patch.yaml
  hack/relatedimages.yaml
  version/version.go
Labels: approved

#888 Ensure MigrationsPerformed is True when done migrating
  controllers/operator/authentication_controller.go
Labels: approved, lgtm, size/M

#897 Add catalog building
  .gitignore
  DEVELOPMENT.md
  Makefile
  common/scripts/multiarch_image.sh
  hack/bundle-render
  hack/channel-render
Labels: approved, size/L

#899 [SC2] Clear redundant endpoint idauth
  controllers/operator/ingress.go
  controllers/operator/resourcestatus.go
  controllers/operator/routes.go
Labels: approved, size/L, lgtm

#900 Ensure MigrationsPerformed is True when done migrating
  apis/oidc.security/v1/zz_generated.deepcopy.go
  apis/operator/v1alpha1/zz_generated.deepcopy.go
  apis/zen.cpd.ibm.com/v1/zz_generated.deepcopy.go
  controllers/operator/authentication_controller.go
Labels: approved, lgtm, size/M

#901 [CD] Enable Client controller watch of Client Secrets
  Makefile
  controllers/oidc.security/client_controller.go
  controllers/oidc.security/clientreg.go
  controllers/oidc.security/zen_registration.go
Labels: approved, lgtm, size/M

#902 [SC2] Enable Client controller watch of Client Secrets
  Makefile
  controllers/oidc.security/client_controller.go
  controllers/oidc.security/clientreg.go
  controllers/oidc.security/zen_registration.go
Labels: approved, lgtm, size/M
