Repository IBM/ibm-iam-operator, pull requests merged in 2024-09, with the labels that each got.

#867 Adding field SecurityContext
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  config/manager/bases/manager.yaml
  controllers/operator/containers.go
  controllers/operator/deployment.go
  controllers/operator/job.go
Labels: approved, lgtm, size/M

#870 fix power and z build issue
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: size/XS, approved

#866 Remove Routes when Zen front door is enabled
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  config/manager/bases/manager.yaml
  controllers/common/utils.go
  controllers/operator/authentication_controller.go
  controllers/operator/routes.go
  controllers/operator/routes_test.go
  controllers/operator/zenextension.go
Labels: size/XXL, approved

#872 sleep introduce for init container
  controllers/operator/containers.go
Labels: size/XS, approved

#853 Added ca crt in provider secret [CD]
  controllers/operator/deployment.go
Labels: size/XS, approved, lgtm

#873 Revert "sleep introduce for init container"
  controllers/operator/containers.go
Labels: size/XS, approved, lgtm

#874 Updating go version from 1.21.8 to 1.21.9
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#871 Clear redundant enpoint idauth
  controllers/operator/ingress.go
  controllers/operator/resourcestatus.go
  controllers/operator/routes.go
  controllers/operator/routes_test.go
  controllers/operator/zenextension.go
Labels: approved, size/L, lgtm

#877 Update version to 4.5.6
  DEVELOPMENT.md
  README.md
  bundle.Dockerfile
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/multiarch_image.sh
  config/manager/overlays/prod/image_env_vars_patch.yaml
  config/manager/overlays/prod/kustomization.yaml
  config/manifests/overlays/prod/annotations_patch.yaml
  config/samples/overlays/prod/authentication_image_patch.yaml
  hack/relatedimages.yaml
  version/version.go
Labels: approved, size/L

#876 Improve Route handling around front door setup
  apis/zen.cpd.ibm.com/v1/zenextension_types.go
  apis/zen.cpd.ibm.com/v1/zz_generated.deepcopy.go
  controllers/common/utils.go
  controllers/operator/authentication_controller.go
  controllers/operator/configmap.go
  controllers/operator/routes.go
  controllers/operator/routes_test.go
  controllers/operator/testdata/crds/routes/route_crd.yaml
  controllers/operator/testdata/crds/zen/zenextension_crd.yaml
  controllers/operator/zenextension.go
  main.go
Labels: approved, size/L

#880 Update aggregated status checks for ZenExtension
  apis/zen.cpd.ibm.com/v1/zenextension_types.go
  controllers/operator/resourcestatus.go
Labels: approved, size/M

#883 Add tests for Route handling with front door
  controllers/operator/operandrequest_test.go
  controllers/operator/routes_test.go
  testing/utils.go
Labels: approved, size/L

#875 go version update
  Dockerfile
  Makefile
  go.mod
Labels: approved, size/S

#881 Build images without requiring qemu
  .gitignore
  Dockerfile
  Makefile
  build/Dockerfile.amd64
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  bundle.Dockerfile
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/multiarch_image.sh
Labels: approved, size/L, lgtm

#885 Update to version 4.9
  DEVELOPMENT.md
  README.md
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/overlays/prod/image_env_vars_patch.yaml
  config/manager/overlays/prod/kustomization.yaml
  config/manifests/overlays/prod/annotations_patch.yaml
  config/samples/overlays/prod/authentication_image_patch.yaml
  hack/relatedimages.yaml
  version/version.go
Labels: size/M

#884 Added ca crt in provider secret
  controllers/operator/deployment.go
Labels: size/XS

#886 Build images without requiring qemu (#881)
  .gitignore
  Dockerfile
  Makefile
  build/Dockerfile.amd64
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  bundle.Dockerfile
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  common/scripts/multiarch_image.sh
Labels: approved, size/L

#882 [SC2] Remove idauth route
  controllers/operator/ingress.go
  controllers/operator/resourcestatus.go
  controllers/operator/routes.go
Labels: approved, size/L

#887 Skip migrating broken Zen documents
  apis/operator/v1alpha1/authentication_types.go
  controllers/common/utils.go
  controllers/oidc.security/client_controller.go
  controllers/operator/routes.go
  migration/migration.go
Labels: approved, size/L

#890 Add BuildKit variable to image builds
  Makefile
Labels: approved, lgtm, size/S

#891 [SC2]Revert idauth removal
  controllers/operator/ingress.go
  controllers/operator/resourcestatus.go
  controllers/operator/routes.go
Labels: approved, size/L
