Repository IBM/ibm-iam-operator, pull requests merged in 2024-01, with the labels that each got.

#725 Trigger build to revert
  README.md
  common/scripts/.githooks/pre-commit
Labels: size/XS

#724 Updated crypto version to 0.17.0
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#723 Support for IAM Multiple Zone Availability
  pkg/controller/authentication/deployment.go
Labels: approved, lgtm, size/M, ok-to-test

#729 Revert -q option on wget calls in image builds
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  common/config/.hadolint.yml
Labels: size/XS, approved, lgtm

#732 Fix Dockerfile arch compile target
  Makefile
  build/Dockerfile.amd64
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/S

#731 Reapply replacement of net and crypto versions
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#730 Update LDAP_SEARCH_TIME_LIMIT default value from 5 to 10
  controllers/operator/configmap.go
Labels: size/XS, approved, lgtm

#733 Update iam.go to resolve pods crash issue
  controllers/oidc.security/iam.go
Labels: size/XS

#734 update base64 icon data
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-iam-operator.clusterserviceversion.yaml
Labels: size/XS, approved

#735 Fix AllNamespaces mode
  main.go
Labels: approved, lgtm, size/M

#736 Fix shadowing of err in Authentication controller
  controllers/operator/authentication_controller.go
Labels: approved, lgtm, size/S

#737 ldap-timeout-update
  pkg/controller/authentication/configmap.go
Labels: size/XS, approved, lgtm

#738 Fixes for RC3
  controllers/oidc.security/client_controller.go
  controllers/oidc.security/clientreg.go
  controllers/oidc.security/zen_registration.go
Labels: approved, size/M

#740 Update to version 4.5.0
  bundle.Dockerfile
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/overlays/dev/image_env_vars_patch.yaml
  config/manager/overlays/dev/kustomization.yaml
  config/manager/overlays/prod/image_env_vars_patch.yaml
  config/manager/overlays/prod/kustomization.yaml
  config/manifests/bases/ibm-iam-operator.clusterserviceversion.yaml
  config/manifests/overlays/dev/annotations_patch.yaml
  config/manifests/overlays/prod/annotations_patch.yaml
  config/samples/overlays/dev/authentication_image_patch.yaml
  config/samples/overlays/prod/authentication_image_patch.yaml
  hack/relatedimages.yaml
  main.go
  version/version.go
Labels: approved, size/L
