Repository IBM/ibm-iam-operator, pull requests merged in 2025-03, with the labels that each got.

#971 Rename charts and templates
  helm-cluster-scoped/Chart.yaml
  helm-cluster-scoped/templates/00_operator.ibm.com_authentications.yaml
  helm-cluster-scoped/templates/01_oidc.security.ibm.com_clients.yaml
  helm-cluster-scoped/templates/10_clusterrole.yaml
  helm-cluster-scoped/templates/11_clusterrolebinding.yaml
Labels: size/XS, approved, lgtm

#969 Merge helm chart changes
  helm-cluster-scoped/templates/00_operator.ibm.com_authentications.yaml
  helm-cluster-scoped/templates/01_oidc.security.ibm.com_clients.yaml
  helm-cluster-scoped/templates/10_clusterrole.yaml
  helm-cluster-scoped/templates/11_clusterrolebinding.yaml
  helm/templates/00-rbac.yaml
  helm/templates/00-serviceaccount.yaml
  helm/templates/02-rolebinding.yaml
  helm/templates/10-deployment.yaml
  helm/values.yaml
Labels: approved, size/L

#976 Add operandbindinfo permissions to chart role
  helm/templates/00-rbac.yaml
Labels: size/XS, approved

#978 V-bump april sc2/4.6.12
  DEVELOPMENT.md
  README.md
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/overlays/prod/image_env_vars_patch.yaml
  config/manager/overlays/prod/kustomization.yaml
  config/manifests/overlays/prod/annotations_patch.yaml
  config/samples/overlays/prod/authentication_image_patch.yaml
  hack/relatedimages.yaml
  version/version.go
Labels: approved, lgtm, size/M

#956 [CD] Ensure oauth-client-map reconciled after creation
  controllers/operator/configmap.go
  controllers/operator/configmap_test.go
Labels: approved, size/L, lgtm

#979 [SC2] Updated golang to 1.24.1
  Makefile
  go.mod
Labels: size/XS, approved

#981 [CD] Upgrade golang to 1.24.1
  Makefile
  go.mod
Labels: size/XS, approved

#987 Support adding custom labels to chart resources
  helm/templates/00-rbac.yaml
  helm/templates/10-deployment.yaml
  helm/values.yaml
Labels: approved, lgtm, size/S

#988 Multi-tenancy with cluster charts
  helm-cluster-scoped/templates/10_clusterrole.yaml
  helm-cluster-scoped/templates/11_clusterrolebinding.yaml
Labels: approved, lgtm, size/S

#980 [SC2] Updated golang.org/x/crypto to v0.35.0
  go.mod
  go.sum
Labels: approved, size/M

#932 add master host to auth service via auth-idp configmap
  controllers/operator/configmap.go
  controllers/operator/configmap_test.go
  controllers/operator/containers.go
  controllers/operator/deployment.go
Labels: approved, lgtm, size/S

#938 [CD] Filter Secret caching
  controllers/common/utils.go
  controllers/oidc.security/client_controller.go
  controllers/oidc.security/errors.go
  controllers/operator/deployment.go
  controllers/operator/job.go
  controllers/operator/routes.go
  controllers/operator/secret.go
  main.go
Labels: approved, size/L, lgtm

#991 [SC2] Update envtest automatically
  Makefile
Labels: approved, lgtm, size/S

#985 update master host to add master_host environment value from configmap
  controllers/operator/configmap.go
  controllers/operator/containers.go
Labels: approved, lgtm, size/S

#990 [CD] Update envtest automatically
  Makefile
Labels: approved, lgtm, size/S

#989 Provide CPFS-specific imagePullPrefix value
  helm/templates/10-deployment.yaml
Labels: size/XS, approved, lgtm

#994 Revert "update master host to add master_host environment value from configmap"
  controllers/operator/configmap.go
  controllers/operator/containers.go
Labels: approved

#977 passthrough route for cert auth
  controllers/operator/constants.go
  controllers/operator/routes.go
  controllers/operator/routes_test.go
Labels: approved, size/M

#997 extra {{end}} causing problems with deployment of latest iam chart
  helm/templates/10-deployment.yaml
Labels: size/XS, approved

#996 add manage-cert-rotation label to certificates
  controllers/operator/certificate.go
Labels: approved, size/M

#998 update image pull prefix for operands
  helm/templates/10-deployment.yaml
Labels: size/XS, approved

#999 [SC2] Update golang.org/x/net to v0.36.0
  go.mod
  go.sum
Labels: size/XS, approved

#970 Always align documented values from Authentication
  controllers/operator/configmap.go
  controllers/operator/configmap_test.go
Labels: approved, size/L

#995 [SC2] - update master host using platform-auth-idp configmap
  controllers/operator/configmap.go
  controllers/operator/containers.go
Labels: approved, size/M

#1000 Set Controller on im-common-service
  controllers/operator/operandrequest.go
Labels: size/XS, approved, lgtm

#1003 Get from API server when cache fails
  controllers/oidc.security/client_controller.go
  controllers/oidc.security/client_controller_config.go
  controllers/operator/authentication_controller.go
  controllers/operator/certificate_test.go
  controllers/operator/configmap.go
  controllers/operator/configmap_test.go
  controllers/operator/operandbindinfo_test.go
  controllers/operator/operandrequest_test.go
  controllers/operator/routes_test.go
  controllers/operator/secret.go
  main.go
Labels: approved, size/L, lgtm

#1004 [sc2]Get from API server when cache fails
  controllers/oidc.security/client_controller.go
  controllers/oidc.security/client_controller_config.go
  controllers/operator/authentication_controller.go
  controllers/operator/operandrequest_test.go
  controllers/operator/secret.go
  main.go
Labels: approved, lgtm, size/M

#1001 Set Controller on im-common-service
  controllers/operator/operandrequest.go
Labels: size/XS, approved

#1007 add key value pairs to log statements
  controllers/operator/configmap.go
Labels: size/XS, approved

#1008 Try reading from API server for Route Secrets
  controllers/operator/routes.go
Labels: size/XS, approved, lgtm
