Repository IBM/ibm-iam-operator, pull requests merged in 2025-01, with the labels that each got.

#925 Always update values in platform-auth-idp when triggered
  controllers/operator/configmap.go
  controllers/operator/configmap_test.go
Labels: approved, lgtm, size/S

#924 Updated golang.org/x/net to v0.33.0
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#919 Watch ibm-cpp-config and product-configmap
  controllers/operator/authentication_controller.go
Labels: approved, size/M

#926 Updated golang.org/x/net v0.33.0 & golang.org/x/crypto v0.31.0[SC2]
  go.mod
  go.sum
Labels: size/M

#927 Updated golang.org/x/net to v0.33.0 (#924)
  go.mod
  go.sum
  version/version.go
Labels: approved, size/M

#928 Updated golang.org/x/net v0.33.0 & golang.org/x/crypto v0.31.0[SC2] (…
  go.mod
  go.sum
  version/version.go
Labels: approved

#930 Remove spec from ZenExtension type
  apis/zen.cpd.ibm.com/v1/zenextension_types.go
  apis/zen.cpd.ibm.com/v1/zz_generated.deepcopy.go
  controllers/operator/authentication_controller.go
  controllers/operator/configmap.go
  controllers/operator/configmap_test.go
  controllers/operator/zenextension.go
Labels: approved, size/XL

#929 Start Client reconciliation sooner
  apis/operator/v1alpha1/authentication_types.go
  controllers/oidc.security/client_controller.go
Labels: approved, size/M

#931 cascade delete on users delete
  database/migrate.go
  database/schema/v1/migrations.go
Labels: approved, size/S

#933 Always add cluster_address_auth for Zen
  controllers/operator/configmap.go
  controllers/operator/configmap_test.go
Labels: approved, size/M

#934 Handle being up with CM and no Authentication
  controllers/operator/authentication_controller.go
Labels: size/XS, approved, lgtm

#935 Only configure OS Auth when on OCP
  controllers/operator/configmap.go
Labels: approved, lgtm, size/S

#937 [SC2] Enable SSL verification on MongoDB migrations
  apis/oidc.security/v1/groupversion_info.go
  controllers/common/resources.go
  controllers/common/utils.go
  controllers/operator/authentication_controller.go
  controllers/operator/configmap.go
  controllers/operator/migration.go
  controllers/operator/secret.go
  database/connectors/options.go
  main.go
Labels: size/XXL, approved
