Repository IBM/ibm-iam-operator, pull requests merged in 2025-05, with the labels that each got.

#1021 Shift migration earlier in Auth reconcile
  controllers/operator/authentication_controller.go
Labels: approved, lgtm, size/M

#1023 Updated golang.org/x/net to v0.39.0[SC2]
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#1028 Rework Authentication status writes
  controllers/operator/authentication_controller.go
  controllers/operator/deployment.go
  controllers/operator/resourcestatus.go
Labels: approved, size/L, lgtm

#1017 Deployment rollout
  controllers/common/resources.go
  controllers/common/secondary.go
  controllers/common/suite_test.go
  controllers/common/utils.go
  controllers/common/utils_test.go
  controllers/operator/authentication_controller.go
  controllers/operator/certificate_test.go
  controllers/operator/configmap.go
  controllers/operator/configmap_test.go
  controllers/operator/deployment.go
  controllers/operator/deployment_test.go
  controllers/operator/matcher.go
  controllers/operator/operandbindinfo.go
  controllers/operator/operandbindinfo_test.go
  controllers/operator/operandrequest_test.go
  controllers/operator/routes.go
  controllers/operator/routes_test.go
  controllers/operator/secret.go
  main.go
Labels: size/XXL, approved

#1024 Updated golang.org/x/net to v0.39.0[CD]
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#1032 June SC2(4.6.15) Version Bump
  DEVELOPMENT.md
  README.md
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/overlays/prod/image_env_vars_patch.yaml
  config/manager/overlays/prod/kustomization.yaml
  config/manifests/overlays/prod/annotations_patch.yaml
  config/samples/overlays/prod/authentication_image_patch.yaml
  hack/relatedimages.yaml
  version/version.go
Labels: approved, lgtm, size/M

#1034 update certificates with manage-cert-rotation: true label
  controllers/operator/certificate.go
Labels: size/XS, approved

#1035 Make bundle at end of update-version
  bundle.Dockerfile
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  hack/update_operator_version
Labels: approved, lgtm, size/S

#1029 HPA implementation
  apis/operator/v1alpha1/authentication_types.go
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_authentications.yaml
  config/crd/bases/operator.ibm.com_authentications.yaml
  config/rbac/role.yaml
  controllers/operator/authentication_controller.go
  controllers/operator/deployment.go
  controllers/operator/hpa.go
  helm-cluster-scoped/templates/00_operator.ibm.com_authentications.yaml
  helm/templates/00-rbac.yaml
Labels: approved, size/L

#1036 Undo unstructured updates in Reconcile
  controllers/common/secondary.go
Labels: approved, lgtm, size/M

#1033 Protect platform-auth-idp from upgrade clobber
  controllers/bootstrap/authentication_bootstrap_controller.go
  controllers/common/constants.go
  controllers/common/utils.go
  controllers/oidc.security/client_controller.go
  controllers/oidc.security/client_controller_config.go
  controllers/oidc.security/clientreg.go
  controllers/operator/authentication_controller.go
  controllers/operator/configmap.go
  controllers/operator/resourcestatus.go
  main.go
Labels: approved, size/L

#1041 updateHPA when profile size change
  controllers/operator/hpa.go
Labels: approved, size/M
