Repository IBM/ibm-iam-operator, pull requests merged in 2025-02, with the labels that each got.

#939 [CD] Update image builds for RH Certification
  Dockerfile
  Makefile
Labels: approved, size/S

#944 [CD] Upgrade go version to 1.23.5
  Makefile
  go.mod
Labels: size/XS, approved, lgtm

#942 [CD] Add nonOLM support
  controllers/operator/deployment.go
  controllers/operator/job.go
  helm-cluster-scoped/Chart.yaml
  helm-cluster-scoped/templates/clusterrole.yaml
  helm-cluster-scoped/templates/clusterrolebinding.yaml
  helm-cluster-scoped/templates/oidc.security.ibm.com_clients.yaml
  helm-cluster-scoped/templates/operator.ibm.com_authentications.yaml
  helm/Chart.yaml
  helm/templates/00-serviceaccount.yaml
  helm/templates/01-role.yaml
  helm/templates/02-rolebinding.yaml
  helm/templates/10-deployment.yaml
  helm/values.yaml
Labels: size/XXL, approved, lgtm

#943 [CD] Remove mandatory cluster-scoped permissions
  Makefile
  apis/operator/v1alpha1/authentication_types.go
  apis/operator/v1alpha1/groupversion_info.go
  apis/operator/v1alpha1/operandrequest_types.go
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_authentications.yaml
  controllers/common/utils.go
  controllers/operator/authentication_controller.go
  controllers/operator/clusterrole.go
  controllers/operator/clusterrolebinding.go
  controllers/operator/configmap.go
  controllers/operator/operandrequest.go
  controllers/operator/resourcestatus.go
  controllers/operator/routes.go
  controllers/operator/zenextension.go
  go.mod
  main.go
Labels: approved, size/XL, lgtm

#946 Update Chart.yaml to match appVersion
  helm-cluster-scoped/Chart.yaml
  helm/Chart.yaml
Labels: size/XS, approved, lgtm

#947 Fix api host retrieval
  controllers/operator/configmap.go
Labels: size/XS, approved, lgtm

#948 Rework ibmcloud-cluster-info reconcile
  controllers/operator/configmap.go
  controllers/operator/configmap_test.go
Labels: size/XS, approved, lgtm

#950 updated helm templates to reference global values
  helm-cluster-scoped/templates/clusterrole.yaml
  helm-cluster-scoped/templates/clusterrolebinding.yaml
  helm/templates/00-serviceaccount.yaml
  helm/templates/01-role.yaml
  helm/templates/02-rolebinding.yaml
  helm/templates/10-deployment.yaml
  helm/values.yaml
Labels: approved, size/S

#951 Miscellaneous bug fixes
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/operator/authentication_controller.go
  controllers/operator/clusterrole.go
  controllers/operator/clusterrolebinding.go
  controllers/operator/configmap.go
Labels: approved, lgtm, size/M

#952 version bump for mar/2025/sc2
  DEVELOPMENT.md
  README.md
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/overlays/prod/image_env_vars_patch.yaml
  config/manager/overlays/prod/kustomization.yaml
  config/manifests/overlays/prod/annotations_patch.yaml
  config/samples/overlays/prod/authentication_image_patch.yaml
  hack/relatedimages.yaml
  version/version.go
Labels: approved, lgtm, size/M

#955 create operator rolebinging in operator namespace
  helm/templates/02-rolebinding.yaml
Labels: size/XS, approved

#962 add component id
  helm-cluster-scoped/templates/clusterrole.yaml
  helm-cluster-scoped/templates/clusterrolebinding.yaml
  helm-cluster-scoped/templates/oidc.security.ibm.com_clients.yaml
  helm-cluster-scoped/templates/operator.ibm.com_authentications.yaml
  helm/templates/00-serviceaccount.yaml
  helm/templates/01-role.yaml
  helm/templates/02-rolebinding.yaml
  helm/templates/10-deployment.yaml
  helm/values.yaml
  version/version.go
Labels: approved, lgtm, size/S

#957 [CD] Skip MongoDB bootstrap CM update when not present
  controllers/operator/migration.go
Labels: approved, size/M

#958 [SC2] Skip MongoDB bootstrap CM update when not present
  controllers/operator/migration.go
Labels: approved, size/M

#963 Update 10-deployment.yaml to add cpfs prefix
  helm/templates/10-deployment.yaml
Labels: approved, size/S

#965 AllNamespace upgrade- check mongo deployment in instance namespace
  controllers/operator/migration.go
Labels: approved, size/S

#966 [sc2]AllNamespace upgrade- check mongo deployment in instance namespace
  controllers/operator/migration.go
Labels: approved, size/S

#967 Dummy commit to trigger new build
  controllers/operator/migration.go
Labels: size/XS, approved, lgtm

#945 [SC2] Upgrade go version to 1.23.5
  Makefile
  go.mod
Labels: size/XS, approved, lgtm
