Repository IBM/ibm-iam-operator, pull requests merged in 2025-04, with the labels that each got.

#1005 [CD] Whitesource Scan - Updated golang.org/x/crypto & golang.org/x/net
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#1012 Handling passthrough route zenfrontdoor
  controllers/operator/routes.go
  controllers/operator/routes_test.go
Labels: approved, size/S

#1016 Version bump May sc2 [ 4.6.13 ]
  DEVELOPMENT.md
  README.md
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/overlays/prod/image_env_vars_patch.yaml
  config/manager/overlays/prod/kustomization.yaml
  config/manifests/overlays/prod/annotations_patch.yaml
  config/samples/overlays/prod/authentication_image_patch.yaml
  hack/relatedimages.yaml
  version/version.go
Labels: approved, lgtm, size/M

#1009 [FORD SAML LOOP SC2] - Update containers.go to add MASTER_PATH
  controllers/operator/configmap.go
  controllers/operator/containers.go
  controllers/operator/ingress.go
  controllers/operator/resourcestatus.go
  controllers/operator/routes.go
  database/connectors/dbconn.go
Labels: approved, size/L

#1022 Version bump June CD [ 4.13 ]
  DEVELOPMENT.md
  README.md
  bundle/manifests/ibm-iam-operator.clusterserviceversion.yaml
  common/scripts/multiarch_image.sh
  config/manager/overlays/prod/image_env_vars_patch.yaml
  config/manager/overlays/prod/kustomization.yaml
  config/manifests/overlays/prod/annotations_patch.yaml
  config/samples/overlays/prod/authentication_image_patch.yaml
  database/schema/v1/tables_test.go
  hack/relatedimages.yaml
  helm-cluster-scoped/Chart.yaml
  helm/Chart.yaml
  helm/templates/10-deployment.yaml
  helm/values.yaml
  version/version.go
Labels: approved, size/L, lgtm
